from __future__ import annotations

import json
from pathlib import Path

from sugar_sugar.build_locations import ascii_fold, build_rows, derivable_tokens, locale_asset_path
from sugar_sugar.location_catalog import LOCALES
from sugar_sugar.location_suggestions import (
    MAX_SUGGESTIONS,
    export_suggestions_asset,
    filter_location_suggestions,
    write_suggestions_asset,
)


def test_filter_requires_two_characters() -> None:
    assert filter_location_suggestions("b") == []
    assert filter_location_suggestions("  p") == []


def test_filter_prefers_prefix_matches_in_english() -> None:
    matches = filter_location_suggestions("ber", locale="en")
    assert matches[0] == "Berlin, Germany"
    assert len(matches) <= MAX_SUGGESTIONS


def test_cjk_and_bg_city_labels_are_one_language() -> None:
    """An English city must not sit next to a translated country name."""
    from sugar_sugar.location_suggestions import place_entries, place_label

    mixed: list[str] = []
    for loc in ("bg", "ja", "ko", "zh"):
        for entry in place_entries():
            label = place_label(entry, loc)
            english = entry.labels["en"]
            if ", " not in label or ", " not in english:
                continue
            city, country = label.split(", ", 1)
            en_city, _, en_country = english.partition(", ")
            if (city == en_city) != (country == en_country):
                mixed.append(f"{loc}: {label}")
    assert not mixed, mixed[:8]


def test_filter_matches_localized_spelling() -> None:
    matches_de = filter_location_suggestions("münc", locale="de")
    assert "München, Deutschland" in matches_de

    matches_de_country = filter_location_suggestions("deutsch", locale="de")
    assert "Deutschland" in matches_de_country

    matches_ru = filter_location_suggestions("моск", locale="ru")
    assert "Москва, Россия" in matches_ru

    matches_zh = filter_location_suggestions("北京", locale="zh")
    assert "北京, 中国" in matches_zh

    matches_ja = filter_location_suggestions("東京", locale="ja")
    assert "東京, 日本" in matches_ja

    matches_ko = filter_location_suggestions("서울", locale="ko")
    assert "서울, 대한민국" in matches_ko

    matches_bg = filter_location_suggestions("софи", locale="bg")
    assert "София, България" in matches_bg

    matches_ja_berlin = filter_location_suggestions("ベルリ", locale="ja")
    assert "ベルリン, ドイツ" in matches_ja_berlin

    matches_ko_seoul = filter_location_suggestions("서울", locale="ko")
    assert "서울, 대한민국" in matches_ko_seoul


def test_filter_ascii_fallback_for_umlauts() -> None:
    matches = filter_location_suggestions("munc", locale="de")
    assert "München, Deutschland" in matches


def test_filter_allows_free_text_not_in_list() -> None:
    """Autocomplete is optional; validation still accepts arbitrary locations."""
    assert filter_location_suggestions("Small Village, Nowhere") == []


def test_every_country_has_up_to_ten_cities() -> None:
    from sugar_sugar.location_catalog import COUNTRY_NAMES, _top_cities_by_country

    top_cities = _top_cities_by_country()
    for country in COUNTRY_NAMES:
        cities = top_cities.get(country, ())
        assert 1 <= len(cities) <= 10


def test_per_locale_assets_match_python_source() -> None:
    """The shipped per-locale files must not drift from the catalog.

    They are generated by `uv run build-locations`; nothing regenerates them at
    runtime, so a catalog edit that is not rebuilt would silently ship stale
    suggestions.
    """
    for locale in LOCALES:
        asset_path = locale_asset_path(locale)
        assert asset_path.exists(), f"missing {asset_path.name} -- run `uv run build-locations`"
        loaded = json.loads(asset_path.read_text(encoding="utf-8"))
        assert loaded == build_rows(locale), f"{asset_path.name} is stale"


def test_no_all_locales_corpus_in_assets() -> None:
    """The 824 KB all-locales corpus must never come back to `assets/`.

    Everything in `assets/` is reachable by URL, and this file used to be
    fetched and parsed on every page load before the location field existed.
    """
    stale = Path(__file__).resolve().parents[1] / "assets" / "location-suggestions.json"
    assert not stale.exists()


def test_per_locale_rows_are_compact() -> None:
    """Rows are `[label, rank]` or `[label, rank, extras]` -- the JS assumes it."""
    rows = build_rows("en")
    assert rows
    for row in rows:
        assert 2 <= len(row) <= 3
        assert isinstance(row[0], str) and row[0]
        assert isinstance(row[1], int)
        if len(row) == 3:
            assert all(isinstance(token, str) and token for token in row[2])


def _search_shipped_rows(locale: str, query: str) -> list[str]:
    """Replay the browser's match/rank over a shipped per-locale file.

    Mirrors `filterPlaces` in assets/location-autocomplete.js, including the way
    the runtime derives each row's lowercase and ASCII-folded tokens from the
    label rather than reading them from the file.
    """
    q = query.strip().lower()
    if len(q) < 2:
        return []
    q_fold = ascii_fold(q)

    prefix: list[tuple[int, str]] = []
    contains: list[tuple[int, str]] = []
    for row in build_rows(locale):
        label, rank = row[0], row[1]
        tokens = sorted(derivable_tokens(label) | {tok.lower() for tok in (row[2] if len(row) > 2 else [])})
        if any(tok.startswith(q) or tok.startswith(q_fold) for tok in tokens):
            prefix.append((rank, label))
        elif any(q in tok or q_fold in tok for tok in tokens):
            contains.append((rank, label))
    return [label for _, label in sorted(prefix) + sorted(contains)][:MAX_SUGGESTIONS]


def test_locale_split_keeps_the_top_suggestion() -> None:
    """Dropping other locales' full labels must not change what ranks first.

    These are the cross-language and alias cases the split could plausibly have
    broken: an English UI reaching "Munchen"/"Peking", and each script finding
    its own city.
    """
    for locale, query, expected in (
        ("en", "ber", "Berlin, Germany"),
        ("en", "munch", "Munich, Germany"),
        ("en", "peking", "Beijing, China"),
        ("de", "munc", "München, Deutschland"),
        ("de", "deutsch", "Deutschland"),
        ("ru", "моск", "Москва, Россия"),
        ("zh", "北京", "北京, 中国"),
        ("zh", "beijing", "北京, 中国"),
    ):
        assert _search_shipped_rows(locale, query)[:1] == [expected]


def test_write_suggestions_asset(tmp_path: Path) -> None:
    target = tmp_path / "location-suggestions.json"
    write_suggestions_asset(target)
    assert json.loads(target.read_text(encoding="utf-8")) == export_suggestions_asset()
