"""Generate ``data/top_cities_by_country.json`` from embedded top-city lists."""

from __future__ import annotations

import json
from pathlib import Path

from sugar_sugar.location_countries import COUNTRY_NAMES

# Up to 10 major cities per country (English names). Capitals first where possible.
TOP_CITIES_BY_COUNTRY: dict[str, list[str]] = {
    "Afghanistan": ["Kabul", "Kandahar", "Herat", "Mazar-i-Sharif", "Jalalabad", "Kunduz", "Ghazni", "Balkh", "Baghlan", "Khost"],
    "Albania": ["Tirana", "Durres", "Vlore", "Shkoder", "Fier", "Korce", "Elbasan", "Berat", "Lushnje", "Pogradec"],
    "Algeria": ["Algiers", "Oran", "Constantine", "Annaba", "Blida", "Batna", "Setif", "Djelfa", "Bejaia", "Tlemcen"],
    "Andorra": ["Andorra la Vella", "Escaldes-Engordany", "Encamp", "Sant Julia de Loria", "La Massana"],
    "Angola": ["Luanda", "Huambo", "Lobito", "Benguela", "Lubango", "Kuito", "Malanje", "Namibe", "Soyo", "Cabinda"],
    "Antigua and Barbuda": ["Saint John's", "All Saints", "Liberta", "Potters Village", "Bolans"],
    "Argentina": ["Buenos Aires", "Cordoba", "Rosario", "Mendoza", "La Plata", "San Miguel de Tucuman", "Mar del Plata", "Salta", "Santa Fe", "San Juan"],
    "Armenia": ["Yerevan", "Gyumri", "Vanadzor", "Vagharshapat", "Abovyan", "Kapan", "Hrazdan", "Armavir", "Charentsavan", "Masis"],
    "Australia": ["Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide", "Gold Coast", "Canberra", "Newcastle", "Wollongong", "Hobart"],
    "Austria": ["Vienna", "Graz", "Linz", "Salzburg", "Innsbruck", "Klagenfurt", "Villach", "Wels", "Sankt Polten", "Dornbirn"],
    "Azerbaijan": ["Baku", "Ganja", "Sumqayit", "Mingachevir", "Lankaran", "Shirvan", "Nakhchivan", "Shaki", "Yevlakh", "Khirdalan"],
    "Bahamas": ["Nassau", "Freeport", "West End", "Coopers Town", "Marsh Harbour"],
    "Bahrain": ["Manama", "Riffa", "Muharraq", "Hamad Town", "Aali", "Isa Town", "Sitra", "Budaiya", "Jidhafs", "Al Malikiyah"],
    "Bangladesh": ["Dhaka", "Chittagong", "Khulna", "Rajshahi", "Sylhet", "Rangpur", "Comilla", "Gazipur", "Narayanganj", "Mymensingh"],
    "Barbados": ["Bridgetown", "Speightstown", "Oistins", "Holetown", "Bathsheba"],
    "Belarus": ["Minsk", "Gomel", "Mogilev", "Vitebsk", "Grodno", "Brest", "Babruysk", "Baranovichi", "Borisov", "Pinsk"],
    "Belgium": ["Brussels", "Antwerp", "Ghent", "Charleroi", "Liege", "Bruges", "Namur", "Leuven", "Mons", "Mechelen"],
    "Belize": ["Belize City", "Belmopan", "San Ignacio", "Orange Walk", "Dangriga", "Corozal", "San Pedro", "Benque Viejo del Carmen"],
    "Benin": ["Cotonou", "Porto-Novo", "Parakou", "Djougou", "Bohicon", "Abomey-Calavi", "Natitingou", "Lokossa", "Ouidah", "Kandi"],
    "Bhutan": ["Thimphu", "Phuntsholing", "Punakha", "Gelephu", "Paro", "Trongsa", "Jakar", "Samdrup Jongkhar"],
    "Bolivia": ["La Paz", "Santa Cruz de la Sierra", "Cochabamba", "Sucre", "Oruro", "Tarija", "Potosi", "Trinidad", "El Alto", "Montero"],
    "Bosnia and Herzegovina": ["Sarajevo", "Banja Luka", "Tuzla", "Zenica", "Mostar", "Bijeljina", "Prijedor", "Brcko", "Doboj", "Cazin"],
    "Botswana": ["Gaborone", "Francistown", "Molepolole", "Maun", "Serowe", "Kanye", "Mahalapye", "Mochudi", "Mogoditshane", "Palapye"],
    "Brazil": ["Sao Paulo", "Rio de Janeiro", "Brasilia", "Salvador", "Fortaleza", "Belo Horizonte", "Manaus", "Curitiba", "Recife", "Porto Alegre"],
    "Brunei": ["Bandar Seri Begawan", "Kuala Belait", "Seria", "Tutong", "Bangar"],
    "Bulgaria": ["Sofia", "Plovdiv", "Varna", "Burgas", "Ruse", "Stara Zagora", "Pleven", "Sliven", "Dobrich", "Shumen"],
    "Burkina Faso": ["Ouagadougou", "Bobo-Dioulasso", "Koudougou", "Banfora", "Ouahigouya", "Pouytenga", "Kaya", "Tenkodogo", "Fada N'gourma", "Hounde"],
    "Burundi": ["Gitega", "Bujumbura", "Muyinga", "Ruyigi", "Ngozi", "Rutana", "Bururi", "Makamba", "Kayanza", "Muramvya"],
    "Cambodia": ["Phnom Penh", "Siem Reap", "Battambang", "Sihanoukville", "Poipet", "Kampong Cham", "Pursat", "Kampong Speu", "Ta Khmau", "Kampot"],
    "Cameroon": ["Douala", "Yaounde", "Garoua", "Bamenda", "Maroua", "Bafoussam", "Bertoua", "Loum", "Kumba", "Nkongsamba"],
    "Canada": ["Toronto", "Montreal", "Vancouver", "Calgary", "Edmonton", "Ottawa", "Winnipeg", "Quebec City", "Hamilton", "Kitchener"],
    "Cape Verde": ["Praia", "Mindelo", "Santa Maria", "Assomada", "Espargos", "Porto Novo", "Ribeira Grande"],
    "Central African Republic": ["Bangui", "Bimbo", "Berberati", "Carnot", "Bambari", "Bouar", "Bossangoa", "Bria", "Bangassou", "Nola"],
    "Chad": ["N'Djamena", "Moundou", "Abeche", "Sarh", "Kelo", "Koumra", "Pala", "Am Timan", "Bongor", "Mongo"],
    "Chile": ["Santiago", "Valparaiso", "Concepcion", "La Serena", "Antofagasta", "Temuco", "Rancagua", "Talca", "Arica", "Chillan"],
    "China": ["Shanghai", "Beijing", "Guangzhou", "Shenzhen", "Chengdu", "Chongqing", "Tianjin", "Wuhan", "Hangzhou", "Nanjing"],
    "Colombia": ["Bogota", "Medellin", "Cali", "Barranquilla", "Cartagena", "Bucaramanga", "Pereira", "Santa Marta", "Ibague", "Cucuta"],
    "Comoros": ["Moroni", "Mutsamudu", "Fomboni", "Domoni", "Tsimbeho"],
    "Congo": ["Brazzaville", "Pointe-Noire", "Dolisie", "Nkayi", "Impfondo", "Ouesso", "Loandjili", "Madingou", "Gamboma", "Owando"],
    "Costa Rica": ["San Jose", "Alajuela", "Cartago", "Heredia", "Liberia", "Puntarenas", "Limon", "San Isidro", "Quesada", "Desamparados"],
    "Croatia": ["Zagreb", "Split", "Rijeka", "Osijek", "Zadar", "Pula", "Slavonski Brod", "Karlovac", "Varazdin", "Sibenik"],
    "Cuba": ["Havana", "Santiago de Cuba", "Camaguey", "Holguin", "Santa Clara", "Guantanamo", "Bayamo", "Las Tunas", "Cienfuegos", "Pinar del Rio"],
    "Cyprus": ["Nicosia", "Limassol", "Larnaca", "Paphos", "Famagusta", "Kyrenia", "Protaras", "Ayia Napa", "Paralimni", "Aradippou"],
    "Czech Republic": ["Prague", "Brno", "Ostrava", "Plzen", "Liberec", "Olomouc", "Ceske Budejovice", "Hradec Kralove", "Usti nad Labem", "Pardubice"],
    "Czechia": ["Prague", "Brno", "Ostrava", "Plzen", "Liberec", "Olomouc", "Ceske Budejovice", "Hradec Kralove", "Usti nad Labem", "Pardubice"],
    "Denmark": ["Copenhagen", "Aarhus", "Odense", "Aalborg", "Esbjerg", "Randers", "Kolding", "Horsens", "Vejle", "Roskilde"],
    "Djibouti": ["Djibouti City", "Ali Sabieh", "Tadjoura", "Obock", "Dikhil", "Arta", "Holhol"],
    "Dominica": ["Roseau", "Portsmouth", "Marigot", "Berekua", "Mahaut", "Salisbury", "Castle Bruce"],
    "Dominican Republic": ["Santo Domingo", "Santiago de los Caballeros", "La Romana", "San Pedro de Macoris", "San Francisco de Macoris", "Puerto Plata", "La Vega", "San Cristobal", "Higuey", "Moca"],
    "Ecuador": ["Quito", "Guayaquil", "Cuenca", "Santo Domingo", "Machala", "Durán", "Manta", "Portoviejo", "Loja", "Ambato"],
    "Egypt": ["Cairo", "Alexandria", "Giza", "Shubra El Kheima", "Port Said", "Suez", "Luxor", "Mansoura", "El Mahalla El Kubra", "Tanta"],
    "El Salvador": ["San Salvador", "Santa Ana", "San Miguel", "Soyapango", "Mejicanos", "Santa Tecla", "Apopa", "Delgado", "Sonsonate", "San Marcos"],
    "Equatorial Guinea": ["Malabo", "Bata", "Ebebiyin", "Aconibe", "Anisoc", "Luba", "Evinayong", "Mongomo"],
    "Eritrea": ["Asmara", "Keren", "Massawa", "Assab", "Mendefera", "Barentu", "Adi Keyh", "Dekemhare", "Akordat", "Teseney"],
    "Estonia": ["Tallinn", "Tartu", "Narva", "Parnu", "Kohtla-Jarve", "Viljandi", "Rakvere", "Maardu", "Sillamae", "Kuressaare"],
    "Eswatini": ["Mbabane", "Manzini", "Big Bend", "Malkerns", "Nhlangano", "Siteki", "Lobamba", "Mhlume"],
    "Ethiopia": ["Addis Ababa", "Dire Dawa", "Mekelle", "Gondar", "Adama", "Hawassa", "Bahir Dar", "Jimma", "Dessie", "Jijiga"],
    "Fiji": ["Suva", "Nadi", "Lautoka", "Labasa", "Ba", "Levuka", "Sigatoka", "Savusavu"],
    "Finland": ["Helsinki", "Espoo", "Tampere", "Vantaa", "Oulu", "Turku", "Jyvaskyla", "Lahti", "Kuopio", "Pori"],
    "France": ["Paris", "Marseille", "Lyon", "Toulouse", "Nice", "Nantes", "Montpellier", "Strasbourg", "Bordeaux", "Lille"],
    "Gabon": ["Libreville", "Port-Gentil", "Franceville", "Oyem", "Moanda", "Mouila", "Lambarene", "Tchibanga", "Koulamoutou", "Bitam"],
    "Gambia": ["Banjul", "Serekunda", "Brikama", "Bakau", "Farafenni", "Lamin", "Sukuta", "Basse Santa Su", "Gunjur", "Soma"],
    "Georgia": ["Tbilisi", "Batumi", "Kutaisi", "Rustavi", "Gori", "Zugdidi", "Poti", "Khashuri", "Samtredia", "Senaki"],
    "Germany": ["Berlin", "Hamburg", "Munich", "Cologne", "Frankfurt", "Stuttgart", "Dusseldorf", "Leipzig", "Dortmund", "Essen"],
    "Ghana": ["Accra", "Kumasi", "Tamale", "Takoradi", "Ashaiman", "Sunyani", "Cape Coast", "Obuasi", "Teshie", "Tema"],
    "Greece": ["Athens", "Thessaloniki", "Patras", "Heraklion", "Larissa", "Volos", "Ioannina", "Chania", "Chalcis", "Kavala"],
    "Grenada": ["Saint George's", "Gouyave", "Grenville", "Victoria", "Sauteurs", "Hillsborough"],
    "Guatemala": ["Guatemala City", "Mixco", "Villa Nueva", "Quetzaltenango", "San Juan Sacatepequez", "Villa Canales", "Escuintla", "Chinautla", "Chimaltenango", "Amatitlan"],
    "Guinea": ["Conakry", "Nzerekore", "Kankan", "Kindia", "Labe", "Gueckedou", "Mamou", "Boke", "Faranah", "Siguiri"],
    "Guinea-Bissau": ["Bissau", "Bafata", "Gabu", "Bissora", "Bolama", "Cacheu", "Bubaque", "Mansoa"],
    "Guyana": ["Georgetown", "Linden", "New Amsterdam", "Anna Regina", "Bartica", "Skeldon", "Rosignol", "Mahaica"],
    "Haiti": ["Port-au-Prince", "Cap-Haitien", "Gonaives", "Les Cayes", "Delmas", "Petion-Ville", "Jacmel", "Jeremie", "Hinche", "Port-de-Paix"],
    "Honduras": ["Tegucigalpa", "San Pedro Sula", "Choloma", "La Ceiba", "El Progreso", "Choluteca", "Comayagua", "Puerto Cortes", "La Lima", "Danli"],
    "Hungary": ["Budapest", "Debrecen", "Szeged", "Miskolc", "Pecs", "Gyor", "Nyiregyhaza", "Kecskemet", "Szekesfehervar", "Szombathely"],
    "Iceland": ["Reykjavik", "Kopavogur", "Hafnarfjordur", "Akureyri", "Reykjanesbaer", "Gardabaer", "Mosfellsbaer", "Akranes", "Selfoss", "Isafjordur"],
    "India": ["Mumbai", "Delhi", "Bangalore", "Hyderabad", "Chennai", "Kolkata", "Ahmedabad", "Pune", "Surat", "Jaipur"],
    "Indonesia": ["Jakarta", "Surabaya", "Bandung", "Medan", "Semarang", "Makassar", "Palembang", "Tangerang", "Depok", "Bekasi"],
    "Iran": ["Tehran", "Mashhad", "Isfahan", "Karaj", "Shiraz", "Tabriz", "Qom", "Ahvaz", "Kermanshah", "Urmia"],
    "Iraq": ["Baghdad", "Basra", "Mosul", "Erbil", "Kirkuk", "Najaf", "Karbala", "Nasiriyah", "Amarah", "Diwaniyah"],
    "Ireland": ["Dublin", "Cork", "Limerick", "Galway", "Waterford", "Drogheda", "Dundalk", "Swords", "Bray", "Navan"],
    "Israel": ["Jerusalem", "Tel Aviv", "Haifa", "Rishon LeZion", "Petah Tikva", "Ashdod", "Netanya", "Beersheba", "Holon", "Bnei Brak"],
    "Italy": ["Rome", "Milan", "Naples", "Turin", "Palermo", "Genoa", "Bologna", "Florence", "Bari", "Catania"],
    "Ivory Coast": ["Abidjan", "Bouake", "Daloa", "San-Pedro", "Korhogo", "Yamoussoukro", "Divo", "Gagnoa", "Anyama", "Man"],
    "Jamaica": ["Kingston", "Montego Bay", "Spanish Town", "Portmore", "Mandeville", "May Pen", "Old Harbour", "Linstead", "Half Way Tree", "Savanna-la-Mar"],
    "Japan": ["Tokyo", "Yokohama", "Osaka", "Nagoya", "Sapporo", "Fukuoka", "Kobe", "Kyoto", "Kawasaki", "Saitama"],
    "Jordan": ["Amman", "Zarqa", "Irbid", "Russeifa", "Aqaba", "Madaba", "Jerash", "Salt", "Mafraq", "Karak"],
    "Kazakhstan": ["Almaty", "Astana", "Shymkent", "Karaganda", "Aktobe", "Taraz", "Pavlodar", "Oskemen", "Semey", "Atyrau"],
    "Kenya": ["Nairobi", "Mombasa", "Kisumu", "Nakuru", "Eldoret", "Thika", "Malindi", "Kitale", "Garissa", "Kakamega"],
    "Kiribati": ["South Tarawa", "Betio", "Bikenibeu", "Teaoraereke", "Bairiki"],
    "Kosovo": ["Pristina", "Prizren", "Ferizaj", "Peja", "Gjakova", "Gjilan", "Mitrovica", "Podujevo", "Vushtrri", "Suhareka"],
    "Kuwait": ["Kuwait City", "Al Ahmadi", "Hawalli", "As Salimiyah", "Sabah as Salim", "Al Farwaniyah", "Al Jahra", "Al Fintas", "Ar Riqqah", "Salwa"],
    "Kyrgyzstan": ["Bishkek", "Osh", "Jalal-Abad", "Karakol", "Tokmok", "Naryn", "Talas", "Balykchy", "Kara-Balta", "Kant"],
    "Laos": ["Vientiane", "Pakse", "Savannakhet", "Luang Prabang", "Thakhek", "Xam Neua", "Phonsavan", "Muang Xay", "Saravan", "Attapeu"],
    "Latvia": ["Riga", "Daugavpils", "Liepaja", "Jelgava", "Jurmala", "Ventspils", "Rezekne", "Valmiera", "Ogre", "Tukums"],
    "Lebanon": ["Beirut", "Tripoli", "Sidon", "Tyre", "Nabatieh", "Jounieh", "Zahle", "Baalbek", "Byblos", "Aley"],
    "Lesotho": ["Maseru", "Teyateyaneng", "Mafeteng", "Hlotse", "Mohale's Hoek", "Maputsoe", "Qacha's Nek", "Quthing", "Peka", "Butha-Buthe"],
    "Liberia": ["Monrovia", "Gbarnga", "Kakata", "Bensonville", "Harper", "Voinjama", "Buchanan", "Zwedru", "New Kru Town", "Pleebo"],
    "Libya": ["Tripoli", "Benghazi", "Misrata", "Tarhuna", "Al Khums", "Zawiya", "Ajdabiya", "Sebha", "Sirte", "Sabha"],
    "Liechtenstein": ["Vaduz", "Schaan", "Balzers", "Triesen", "Eschen", "Mauren", "Triesenberg", "Ruggell", "Gamprin", "Schellenberg"],
    "Lithuania": ["Vilnius", "Kaunas", "Klaipeda", "Siauliai", "Panevezys", "Alytus", "Marijampole", "Mazeikiai", "Jonava", "Utena"],
    "Luxembourg": ["Luxembourg City", "Esch-sur-Alzette", "Differdange", "Dudelange", "Ettelbruck", "Diekirch", "Wiltz", "Echternach", "Rumelange", "Grevenmacher"],
    "Madagascar": ["Antananarivo", "Toamasina", "Antsirabe", "Mahajanga", "Fianarantsoa", "Toliara", "Antsiranana", "Ambovombe", "Ambatondrazaka", "Moramanga"],
    "Malawi": ["Lilongwe", "Blantyre", "Mzuzu", "Zomba", "Kasungu", "Mangochi", "Karonga", "Salima", "Nkhotakota", "Liwonde"],
    "Malaysia": ["Kuala Lumpur", "George Town", "Ipoh", "Shah Alam", "Petaling Jaya", "Johor Bahru", "Malacca City", "Kota Kinabalu", "Kuching", "Kuantan"],
    "Maldives": ["Male", "Addu City", "Fuvahmulah", "Kulhudhuffushi", "Thinadhoo", "Naifaru", "Hithadhoo", "Viligili"],
    "Mali": ["Bamako", "Sikasso", "Mopti", "Koutiala", "Kayes", "Segou", "Gao", "Markala", "Kolokani", "Kati"],
    "Malta": ["Valletta", "Birkirkara", "Mosta", "Qormi", "Zabbar", "Sliema", "San Gwann", "Naxxar", "Paola", "Hamrun"],
    "Marshall Islands": ["Majuro", "Ebeye", "Jabor", "Wotje", "Jaluit"],
    "Mauritania": ["Nouakchott", "Nouadhibou", "Kiffa", "Kaedi", "Rosso", "Zouerate", "Atar", "Nema", "Aleg", "Selibaby"],
    "Mauritius": ["Port Louis", "Beau Bassin-Rose Hill", "Vacoas-Phoenix", "Curepipe", "Quatre Bornes", "Triolet", "Goodlands", "Centre de Flacq", "Mahebourg", "Saint Pierre"],
    "Mexico": ["Mexico City", "Guadalajara", "Monterrey", "Puebla", "Tijuana", "Leon", "Juarez", "Zapopan", "Merida", "Cancun"],
    "Micronesia": ["Palikir", "Weno", "Tofol", "Kolonia", "Colonia"],
    "Moldova": ["Chisinau", "Tiraspol", "Balti", "Bender", "Ribnita", "Cahul", "Ungheni", "Soroca", "Orhei", "Comrat"],
    "Monaco": ["Monaco", "Monte Carlo", "La Condamine", "Fontvieille"],
    "Mongolia": ["Ulaanbaatar", "Erdenet", "Darkhan", "Choibalsan", "Murun", "Khovd", "Olgii", "Bayankhongor", "Ulaangom", "Sainshand"],
    "Montenegro": ["Podgorica", "Niksic", "Pljevlja", "Bijelo Polje", "Cetinje", "Bar", "Herceg Novi", "Budva", "Berane", "Ulcinj"],
    "Morocco": ["Casablanca", "Rabat", "Fes", "Marrakesh", "Tangier", "Agadir", "Meknes", "Oujda", "Kenitra", "Tetouan"],
    "Mozambique": ["Maputo", "Matola", "Beira", "Nampula", "Chimoio", "Nacala", "Quelimane", "Tete", "Lichinga", "Pemba"],
    "Myanmar": ["Yangon", "Mandalay", "Naypyidaw", "Mawlamyine", "Bago", "Pathein", "Monywa", "Meiktila", "Myitkyina", "Taunggyi"],
    "Namibia": ["Windhoek", "Rundu", "Walvis Bay", "Oshakati", "Swakopmund", "Katima Mulilo", "Grootfontein", "Rehoboth", "Otjiwarongo", "Okahandja"],
    "Nauru": ["Yaren", "Denigomodu", "Aiwo", "Meneng", "Anabar"],
    "Nepal": ["Kathmandu", "Pokhara", "Lalitpur", "Bharatpur", "Biratnagar", "Birgunj", "Dharan", "Butwal", "Hetauda", "Janakpur"],
    "Netherlands": ["Amsterdam", "Rotterdam", "The Hague", "Utrecht", "Eindhoven", "Groningen", "Tilburg", "Almere", "Breda", "Nijmegen"],
    "New Zealand": ["Auckland", "Wellington", "Christchurch", "Hamilton", "Tauranga", "Dunedin", "Palmerston North", "Napier", "Porirua", "New Plymouth"],
    "Nicaragua": ["Managua", "Leon", "Masaya", "Tipitapa", "Chinandega", "Matagalpa", "Esteli", "Granada", "Juigalpa", "Jinotepe"],
    "Niger": ["Niamey", "Zinder", "Maradi", "Agadez", "Tahoua", "Dosso", "Diffa", "Arlit", "Birni N'Konni", "Tessaoua"],
    "Nigeria": ["Lagos", "Kano", "Ibadan", "Abuja", "Port Harcourt", "Benin City", "Kaduna", "Maiduguri", "Zaria", "Aba"],
    "North Korea": ["Pyongyang", "Hamhung", "Chongjin", "Nampo", "Wonsan", "Sinuiju", "Tanchon", "Kaechon", "Kaesong", "Sariwon"],
    "North Macedonia": ["Skopje", "Bitola", "Kumanovo", "Prilep", "Tetovo", "Veles", "Shtip", "Ohrid", "Gostivar", "Strumica"],
    "Norway": ["Oslo", "Bergen", "Trondheim", "Stavanger", "Drammen", "Fredrikstad", "Kristiansand", "Sandnes", "Tromso", "Sarpsborg"],
    "Oman": ["Muscat", "Salalah", "Sohar", "Seeb", "Bawshar", "Ibri", "Sur", "Nizwa", "Barka", "Rustaq"],
    "Pakistan": ["Karachi", "Lahore", "Faisalabad", "Rawalpindi", "Multan", "Hyderabad", "Gujranwala", "Peshawar", "Quetta", "Islamabad"],
    "Palau": ["Ngerulmud", "Koror", "Melekeok", "Airai", "Ngerekebesang"],
    "Palestine": ["Gaza City", "Hebron", "Nablus", "Ramallah", "Jenin", "Tulkarm", "Qalqilya", "Bethlehem", "Jericho", "Rafah"],
    "Panama": ["Panama City", "San Miguelito", "David", "Arraijan", "Colon", "La Chorrera", "Santiago", "Chitre", "Penonome", "Aguadulce"],
    "Papua New Guinea": ["Port Moresby", "Lae", "Mount Hagen", "Madang", "Goroka", "Kokopo", "Mendi", "Kimbe", "Alotau", "Popondetta"],
    "Paraguay": ["Asuncion", "Ciudad del Este", "San Lorenzo", "Luque", "Capiata", "Lambare", "Fernando de la Mora", "Limpio", "Encarnacion", "Caaguazu"],
    "Peru": ["Lima", "Arequipa", "Trujillo", "Chiclayo", "Piura", "Iquitos", "Cusco", "Huancayo", "Tacna", "Juliaca"],
    "Philippines": ["Manila", "Quezon City", "Davao City", "Caloocan", "Cebu City", "Zamboanga City", "Taguig", "Antipolo", "Pasig", "Cagayan de Oro"],
    "Poland": ["Warsaw", "Krakow", "Lodz", "Wroclaw", "Poznan", "Gdansk", "Szczecin", "Bydgoszcz", "Lublin", "Katowice"],
    "Portugal": ["Lisbon", "Porto", "Vila Nova de Gaia", "Amadora", "Braga", "Coimbra", "Funchal", "Setubal", "Almada", "Agualva-Cacem"],
    "Qatar": ["Doha", "Al Wakrah", "Al Khor", "Al Rayyan", "Umm Salal", "Dukhan", "Mesaieed", "Al Shamal", "Al Daayen", "Lusail"],
    "Romania": ["Bucharest", "Cluj-Napoca", "Timisoara", "Iasi", "Constanta", "Craiova", "Brasov", "Galati", "Ploiesti", "Oradea"],
    "Russia": ["Moscow", "Saint Petersburg", "Novosibirsk", "Yekaterinburg", "Kazan", "Nizhny Novgorod", "Chelyabinsk", "Samara", "Omsk", "Rostov-on-Don"],
    "Rwanda": ["Kigali", "Butare", "Gitarama", "Ruhengeri", "Gisenyi", "Byumba", "Cyangugu", "Kibungo", "Rwamagana", "Kibuye"],
    "Saint Kitts and Nevis": ["Basseterre", "Charlestown", "Sandy Point Town", "Cayon", "Dieppe Bay Town"],
    "Saint Lucia": ["Castries", "Bisee", "Vieux Fort", "Micoud", "Dennery", "Soufriere", "Gros Islet", "Anse La Raye"],
    "Saint Vincent and the Grenadines": ["Kingstown", "Georgetown", "Byera Village", "Barrouallie", "Port Elizabeth", "Chateaubelair"],
    "Samoa": ["Apia", "Vaitele", "Faleula", "Siusega", "Malie", "Fasitoouta", "Vaiusu", "Leulumoega"],
    "San Marino": ["San Marino", "Serravalle", "Borgo Maggiore", "Domagnano", "Fiorentino", "Acquaviva", "Faetano", "Chiesanuova"],
    "Sao Tome and Principe": ["Sao Tome", "Santo Amaro", "Neves", "Trindade", "Santana", "Guadalupe", "Sao Joao dos Angolares"],
    "Saudi Arabia": ["Riyadh", "Jeddah", "Mecca", "Medina", "Dammam", "Khobar", "Tabuk", "Buraidah", "Khamis Mushait", "Abha"],
    "Senegal": ["Dakar", "Touba", "Thies", "Rufisque", "Kaolack", "Mbour", "Ziguinchor", "Saint-Louis", "Diourbel", "Louga"],
    "Serbia": ["Belgrade", "Novi Sad", "Nis", "Kragujevac", "Subotica", "Zrenjanin", "Pancevo", "Cacak", "Novi Pazar", "Leskovac"],
    "Seychelles": ["Victoria", "Anse Boileau", "Beau Vallon", "Cascade", "Takamaka", "Anse Royale", "Port Glaud"],
    "Sierra Leone": ["Freetown", "Bo", "Kenema", "Makeni", "Koidu", "Lunsar", "Port Loko", "Waterloo", "Kabala", "Magburaka"],
    "Singapore": ["Singapore"],
    "Slovakia": ["Bratislava", "Kosice", "Presov", "Zilina", "Nitra", "Banska Bystrica", "Trnava", "Trencin", "Martin", "Poprad"],
    "Slovenia": ["Ljubljana", "Maribor", "Celje", "Kranj", "Velenje", "Koper", "Novo Mesto", "Ptuj", "Trbovlje", "Kamnik"],
    "Solomon Islands": ["Honiara", "Auki", "Gizo", "Kirakira", "Buala", "Tulagi", "Lata", "Munda"],
    "Somalia": ["Mogadishu", "Hargeisa", "Bosaso", "Kismayo", "Merca", "Galkayo", "Berbera", "Garowe", "Baidoa", "Burao"],
    "South Africa": ["Johannesburg", "Cape Town", "Durban", "Pretoria", "Port Elizabeth", "Bloemfontein", "East London", "Polokwane", "Nelspruit", "Kimberley"],
    "South Korea": ["Seoul", "Busan", "Incheon", "Daegu", "Daejeon", "Gwangju", "Suwon", "Ulsan", "Changwon", "Goyang"],
    "South Sudan": ["Juba", "Winejok", "Yambio", "Malakal", "Wau", "Kuacjok", "Bor", "Aweil", "Rumbek", "Torit"],
    "Spain": ["Madrid", "Barcelona", "Valencia", "Seville", "Zaragoza", "Malaga", "Murcia", "Palma", "Las Palmas", "Bilbao"],
    "Sri Lanka": ["Colombo", "Dehiwala-Mount Lavinia", "Moratuwa", "Jaffna", "Negombo", "Kandy", "Trincomalee", "Galle", "Batticaloa", "Anuradhapura"],
    "Sudan": ["Khartoum", "Omdurman", "Khartoum North", "Port Sudan", "Kassala", "El Obeid", "Nyala", "Wad Madani", "El Fasher", "Kosti"],
    "Suriname": ["Paramaribo", "Lelydorp", "Nieuw Nickerie", "Moengo", "Nieuw Amsterdam", "Marienburg", "Albina", "Groningen", "Brownsweg"],
    "Sweden": ["Stockholm", "Gothenburg", "Malmo", "Uppsala", "Vasteras", "Orebro", "Linkoping", "Helsingborg", "Jonkoping", "Norrkoping"],
    "Switzerland": ["Zurich", "Geneva", "Basel", "Lausanne", "Bern", "Winterthur", "Lucerne", "St. Gallen", "Lugano", "Biel"],
    "Syria": ["Damascus", "Aleppo", "Homs", "Latakia", "Hama", "Raqqa", "Deir ez-Zor", "Hasaka", "Qamishli", "Tartus"],
    "Taiwan": ["Taipei", "Kaohsiung", "Taichung", "Tainan", "Banqiao", "Hsinchu", "Taoyuan", "Keelung", "Chiayi", "Changhua"],
    "Tajikistan": ["Dushanbe", "Khujand", "Kulob", "Bokhtar", "Istaravshan", "Vahdat", "Konibodom", "Tursunzoda", "Isfara", "Panjakent"],
    "Tanzania": ["Dar es Salaam", "Mwanza", "Arusha", "Dodoma", "Mbeya", "Morogoro", "Tanga", "Kahama", "Tabora", "Zanzibar City"],
    "Thailand": ["Bangkok", "Nonthaburi", "Nakhon Ratchasima", "Chiang Mai", "Hat Yai", "Udon Thani", "Pak Kret", "Khon Kaen", "Pattaya", "Phuket"],
    "Timor-Leste": ["Dili", "Baucau", "Maliana", "Suai", "Lospalos", "Same", "Aileu", "Gleno", "Liquica", "Viqueque"],
    "Togo": ["Lome", "Sokode", "Kara", "Kpalime", "Atakpame", "Bassar", "Tsevie", "Dapaong", "Tchamba", "Aného"],
    "Tonga": ["Nuku'alofa", "Neiafu", "Haveluloto", "Vaini", "Pangai", "Ohonua", "Hihifo"],
    "Trinidad and Tobago": ["Port of Spain", "San Fernando", "Chaguanas", "Arima", "Point Fortin", "Tunapuna", "Scarborough", "Sangre Grande", "Princes Town", "Rio Claro"],
    "Tunisia": ["Tunis", "Sfax", "Sousse", "Kairouan", "Bizerte", "Gabes", "Ariana", "Gafsa", "Monastir", "Ben Arous"],
    "Turkey": ["Istanbul", "Ankara", "Izmir", "Bursa", "Antalya", "Adana", "Gaziantep", "Konya", "Mersin", "Kayseri"],
    "Turkmenistan": ["Ashgabat", "Turkmenabat", "Dasoguz", "Mary", "Balkanabat", "Bayramaly", "Turkmenbashi", "Tejen", "Abadan", "Yoloten"],
    "Tuvalu": ["Funafuti", "Savave", "Tanrake", "Tonga", "Asau"],
    "Uganda": ["Kampala", "Gulu", "Lira", "Mbarara", "Jinja", "Mbale", "Mukono", "Masaka", "Entebbe", "Arua"],
    "Ukraine": ["Kyiv", "Kharkiv", "Odesa", "Dnipro", "Donetsk", "Lviv", "Zaporizhzhia", "Kryvyi Rih", "Mykolaiv", "Mariupol"],
    "United Arab Emirates": ["Dubai", "Abu Dhabi", "Sharjah", "Al Ain", "Ajman", "Ras Al Khaimah", "Fujairah", "Umm Al Quwain", "Khor Fakkan", "Kalba"],
    "United Kingdom": ["London", "Birmingham", "Manchester", "Glasgow", "Leeds", "Liverpool", "Bristol", "Sheffield", "Edinburgh", "Leicester"],
    "United States": ["New York", "Los Angeles", "Chicago", "Houston", "Phoenix", "Philadelphia", "San Antonio", "San Diego", "Dallas", "San Jose"],
    "Uruguay": ["Montevideo", "Salto", "Ciudad de la Costa", "Paysandu", "Las Piedras", "Rivera", "Maldonado", "Tacuarembo", "Melo", "Mercedes"],
    "Uzbekistan": ["Tashkent", "Samarkand", "Namangan", "Andijan", "Nukus", "Bukhara", "Qarshi", "Fergana", "Kokand", "Margilan"],
    "Vanuatu": ["Port Vila", "Luganville", "Norsup", "Sola", "Lakatoro", "Isangel", "Saratamata"],
    "Vatican City": ["Vatican City"],
    "Venezuela": ["Caracas", "Maracaibo", "Valencia", "Barquisimeto", "Maracay", "Ciudad Guayana", "Barcelona", "Maturin", "Ciudad Bolivar", "San Cristobal"],
    "Vietnam": ["Ho Chi Minh City", "Hanoi", "Haiphong", "Da Nang", "Can Tho", "Bien Hoa", "Nha Trang", "Hue", "Vung Tau", "Quy Nhon"],
    "Yemen": ["Sanaa", "Aden", "Taiz", "Hodeidah", "Ibb", "Dhamar", "Mukalla", "Zinjibar", "Sayyan", "Amran"],
    "Zambia": ["Lusaka", "Kitwe", "Ndola", "Kabwe", "Chingola", "Mufulira", "Livingstone", "Luanshya", "Kasama", "Chipata"],
    "Zimbabwe": ["Harare", "Bulawayo", "Chitungwiza", "Mutare", "Gweru", "Kwekwe", "Kadoma", "Masvingo", "Chinhoyi", "Marondera"],
}


def main() -> None:
    output = Path(__file__).resolve().parent / "data" / "top_cities_by_country.json"
    output.parent.mkdir(parents=True, exist_ok=True)
    payload: dict[str, list[str]] = {}
    for country in COUNTRY_NAMES:
        cities = TOP_CITIES_BY_COUNTRY.get(country, [])
        if not cities:
            cities = [country]
        payload[country] = cities[:10]
    output.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
    total = sum(len(v) for v in payload.values())
    print(f"Wrote {len(payload)} countries, {total} cities -> {output}")


if __name__ == "__main__":
    main()
