"""Word and phrase glossary for BIG IDEAs food-note display.

Built from every ``logged_food`` / ``searched_food`` / ``unit`` token in the
16 published BIG IDEAs food logs. Brand names stay English; food words and
units are translated. Exact phrases win over single words.
"""
from __future__ import annotations

from typing import Final

_LOCALES: Final[tuple[str, ...]] = ("de", "fr", "es", "ro", "ru", "uk", "zh")


def _t(*values: str) -> dict[str, str]:
    if len(values) != len(_LOCALES):
        raise ValueError(f"expected {len(_LOCALES)} locale values, got {len(values)}")
    return dict(zip(_LOCALES, values))


# Longest phrases first at lookup time. Keys are lowercase English.
PHRASES: dict[str, dict[str, str]] = {
    "extra virgin olive oil": _t("natives Olivenöl extra", "huile d'olive extra vierge", "aceite de oliva virgen extra", "ulei de măsline extravirgin", "оливковое масло extra virgin", "оливкова олія extra virgin", "特级初榨橄榄油"),
    "balsamic vinegar": _t("Balsamicoessig", "vinaigre balsamique", "vinagre balsámico", "oțet balsamic", "бальзамический уксус", "бальзамічний оцет", "香醋"),
    "red bell pepper": _t("rote Paprika", "poivron rouge", "pimiento rojo", "ardei gras roșu", "красный перец", "червоний перець", "红甜椒"),
    "green bell pepper": _t("grüne Paprika", "poivron vert", "pimiento verde", "ardei gras verde", "зелёный перец", "зелений перець", "青甜椒"),
    "bell pepper": _t("Paprika", "poivron", "pimiento", "ardei gras", "болгарский перец", "болгарський перець", "甜椒"),
    "salad greens": _t("Salatblätter", "feuilles de salade", "hojas de ensalada", "frunze de salată", "листья салата", "листя салату", "沙拉菜"),
    "olive oil": _t("Olivenöl", "huile d'olive", "aceite de oliva", "ulei de măsline", "оливковое масло", "оливкова олія", "橄榄油"),
    "peanut butter": _t("Erdnussbutter", "beurre de cacahuète", "mantequilla de maní", "unt de arahide", "арахисовая паста", "арахісова паста", "花生酱"),
    "ice cream sandwich": _t("Eiscreme-Sandwich", "sandwich glacé", "sándwich de helado", "sandwich cu înghețată", "мороженое-сэндвич", "сендвіч з морозивом", "冰淇淋三明治"),
    "ice cream": _t("Eiscreme", "glace", "helado", "înghețată", "мороженое", "морозиво", "冰淇淋"),
    "cottage cheese": _t("Hüttenkäse", "fromage blanc", "requesón", "brânză de vaci", "творог", "сир кисломолочний", "cottage cheese"),
    "cream cheese": _t("Frischkäse", "fromage à la crème", "queso crema", "cremă de brânză", "сливочный сыр", "вершковий сир", "奶油奶酪"),
    "sour cream": _t("Sauerrahm", "crème fraîche", "crema agria", "smântână", "сметана", "сметана", "酸奶油"),
    "french fries": _t("Pommes frites", "frites", "patatas fritas", "cartofi prăjiți", "картофель фри", "картопля фрі", "薯条"),
    "chicken breast": _t("Hähnchenbrust", "blanc de poulet", "pechuga de pollo", "piept de pui", "куриная грудка", "куряча грудка", "鸡胸肉"),
    "chicken leg": _t("Hähnchenschenkel", "cuisse de poulet", "muslo de pollo", "pulpă de pui", "куриная ножка", "куряча ніжка", "鸡腿"),
    "chicken thigh": _t("Hähnchenkeule", "cuisse de poulet", "muslo de pollo", "pulpă de pui", "куриное бедро", "куряче стегно", "鸡大腿"),
    "chicken wing": _t("Hähnchenflügel", "aile de poulet", "ala de pollo", "aripă de pui", "куриное крыло", "куряче крило", "鸡翅"),
    "chicken noodle soup": _t("Hühnchen-Nudelsuppe", "soupe poulet-nouilles", "sopa de pollo con fideos", "supă de pui cu tăiței", "куриный суп с лапшой", "курячий суп з локшиною", "鸡面汤"),
    "sweet potato": _t("Süßkartoffel", "patate douce", "batata", "cartof dulce", "батат", "батат", "红薯"),
    "baked potato": _t("Ofenkartoffel", "pomme de terre au four", "patata asada", "cartof copt", "печёный картофель", "печена картопля", "烤土豆"),
    "mashed potatoes": _t("Kartoffelpüree", "purée de pommes de terre", "puré de patata", "piure de cartofi", "картофельное пюре", "картопляне пюре", "土豆泥"),
    "mashed potato": _t("Kartoffelpüree", "purée de pommes de terre", "puré de patata", "piure de cartofi", "картофельное пюре", "картопляне пюре", "土豆泥"),
    "hard boiled egg": _t("hartgekochtes Ei", "œuf dur", "huevo duro", "ou fiert tare", "яйцо вкрутую", "яйце круто", "水煮蛋"),
    "hard boiled eggs": _t("hartgekochte Eier", "œufs durs", "huevos duros", "ouă fierte tari", "яйца вкрутую", "яйця круто", "水煮蛋"),
    "boiled eggs": _t("gekochte Eier", "œufs bouillis", "huevos cocidos", "ouă fierte", "варёные яйца", "варені яйця", "煮蛋"),
    "fried egg": _t("Spiegelei", "œuf au plat", "huevo frito", "ou ochi", "яичница", "яєчня", "煎蛋"),
    "scrambled eggs": _t("Rührei", "œufs brouillés", "huevos revueltos", "ouă jumări", "яичница-болтунья", "яєчня-бовтанка", "炒蛋"),
    "greek yogurt": _t("griechischer Joghurt", "yaourt grec", "yogur griego", "iaurt grecesc", "греческий йогурт", "грецький йогурт", "希腊酸奶"),
    "dark chocolate": _t("Zartbitterschokolade", "chocolat noir", "chocolate negro", "ciocolată neagră", "тёмный шоколад", "чорний шоколад", "黑巧克力"),
    "ranch dressing": _t("Ranch-Dressing", "sauce ranch", "aderezo ranch", "sos ranch", "соус ранч", "соус ранч", "牧场酱"),
    "blue cheese": _t("Blauschimmelkäse", "roquefort", "queso azul", "brânză albastră", "голубой сыр", "блакитний сир", "蓝纹奶酪"),
    "half and half": _t("Half-and-half", "half and half", "mitad y mitad", "half and half", "полусливки", "напіввершки", "半奶油"),
    "orange juice": _t("Orangensaft", "jus d'orange", "zumo de naranja", "suc de portocale", "апельсиновый сок", "апельсиновий сік", "橙汁"),
    "apple juice": _t("Apfelsaft", "jus de pomme", "zumo de manzana", "suc de mere", "яблочный сок", "яблучний сік", "苹果汁"),
    "lemon juice": _t("Zitronensaft", "jus de citron", "zumo de limón", "suc de lămâie", "лимонный сок", "лимонний сік", "柠檬汁"),
    "green beans": _t("grüne Bohnen", "haricots verts", "judías verdes", "fasole verde", "зелёная фасоль", "зелена квасоля", "四季豆"),
    "green bean": _t("grüne Bohne", "haricot vert", "judía verde", "fasole verde", "зелёная фасоль", "зелена квасоля", "四季豆"),
    "black beans": _t("schwarze Bohnen", "haricots noirs", "frijoles negros", "fasole neagră", "чёрная фасоль", "чорна квасоля", "黑豆"),
    "black coffee": _t("schwarzer Kaffee", "café noir", "café negro", "cafea neagră", "чёрный кофе", "чорна кава", "黑咖啡"),
    "berry smoothie": _t("Beeren-Smoothie", "smoothie aux baies", "batido de frutos rojos", "smoothie de fructe de pădure", "ягодный смузи", "ягідний смузі", "浆果冰沙"),
    "strawberry smoothie": _t("Erdbeer-Smoothie", "smoothie à la fraise", "batido de fresa", "smoothie de căpșuni", "клубничный смузи", "полуничний смузі", "草莓冰沙"),
    "grilled cheese": _t("Käsesandwich", "croque-monsieur", "sándwich de queso", "sandwich cu brânză", "горячий сырный сэндвич", "гарячий сирний сендвіч", "烤奶酪三明治"),
    "hot dog": _t("Hotdog", "hot-dog", "perrito caliente", "hot dog", "хот-дог", "хот-дог", "热狗"),
    "hot chocolate": _t("Heiße Schokolade", "chocolat chaud", "chocolate caliente", "ciocolată caldă", "горячий шоколад", "гарячий шоколад", "热巧克力"),
    "potato chips": _t("Kartoffelchips", "chips", "patatas fritas", "chipsuri de cartofi", "картофельные чипсы", "картопляні чіпси", "薯片"),
    "potato chip": _t("Kartoffelchip", "chip", "patata frita", "chips de cartofi", "картофельный чипс", "картопляний чіп", "薯片"),
    "tortilla chips": _t("Tortilla-Chips", "chips de tortilla", "totopos", "chipsuri de tortilla", "чипсы тортилья", "чіпси тортілья", "玉米片"),
    "pita bread": _t("Pitabrot", "pain pita", "pan de pita", "lipie", "пита", "піта", "皮塔饼"),
    "whole wheat": _t("Vollkorn", "blé complet", "trigo integral", "grâu integral", "цельнозерновой", "цільнозерновий", "全麦"),
    "ground beef": _t("Rinderhack", "bœuf haché", "carne picada", "carne tocată de vită", "говяжий фарш", "яловичий фарш", "牛肉末"),
    "peanut butter cup": _t("Erdnussbutter-Praline", "cup beurre de cacahuète", "copa de mantequilla de maní", "cupă cu unt de arahide", "конфета с арахисовой пастой", "цукерка з арахісовою пастою", "花生酱杯"),
    "cream of wheat": _t("Weizengrießbrei", "crème de blé", "crema de trigo", "griș", "манная каша", "манна каша", "小麦糊"),
    "corn flakes": _t("Cornflakes", "corn-flakes", "copos de maíz", "fulgi de porumb", "кукурузные хлопья", "кукурудзяні пластівці", "玉米片"),
    "frosted flakes": _t("Frosties", "frosties", "copos azucarados", "fulgi glazurați", "глазированные хлопья", "глазуровані пластівці", "糖霜麦片"),
    "refried beans": _t("Bohnenmus", "haricots refritos", "frijoles refritos", "fasole prăjită", "жареная фасоль", "смажена квасоля", "炸豆泥"),
    "brussel sprouts": _t("Rosenkohl", "choux de Bruxelles", "coless de Bruselas", "varză de Bruxelles", "брюссельская капуста", "брюссельська капуста", "抱子甘蓝"),
    "brussels sprouts": _t("Rosenkohl", "choux de Bruxelles", "coles de Bruselas", "varză de Bruxelles", "брюссельская капуста", "брюссельська капуста", "抱子甘蓝"),
    "string beans": _t("grüne Bohnen", "haricots verts", "judías verdes", "fasole păstăi", "стручковая фасоль", "стручкова квасоля", "豇豆"),
    "roast beef": _t("Rinderbraten", "rosbif", "rosbif", "roast beef", "ростбиф", "ростбіф", "烤牛肉"),
    "mountain dew": _t("Mountain Dew", "Mountain Dew", "Mountain Dew", "Mountain Dew", "Mountain Dew", "Mountain Dew", "Mountain Dew"),
    "thousand island": _t("Thousand-Island-Dressing", "sauce thousand island", "aderezo mil islas", "sos thousand island", "соус тысяча островов", "соус тисяча островів", "千岛酱"),
    "trail mix": _t("Studentenfutter", "mélange de fruits secs", "mix de frutos secos", "mix de fructe uscate", "ореховая смесь", "суміш горіхів", "什锦果仁"),
    "navel orange": _t("Navelorange", "orange navel", "naranja navel", "portocală navel", "пупочный апельсин", "пупковий апельсин", "脐橙"),
    "sloppy joe": _t("Sloppy Joe", "sloppy joe", "sloppy joe", "sloppy joe", "слоппи джо", "слоппі джо", "斯洛比汉堡"),
    "steak fries": _t("Steakhouse-Pommes", "frites steakhouse", "patatas steak", "cartofi steakhouse", "стейк-фри", "стейк-фрі", "牛排薯条"),
    "cara cara": _t("Cara Cara", "Cara Cara", "Cara Cara", "Cara Cara", "Cara Cara", "Cara Cara", "卡拉卡拉橙"),
}

WORDS: dict[str, dict[str, str]] = {
    "chicken": _t("Hähnchen", "poulet", "pollo", "pui", "курица", "курка", "鸡肉"),
    "milk": _t("Milch", "lait", "leche", "lapte", "молоко", "молоко", "牛奶"),
    "coffee": _t("Kaffee", "café", "café", "cafea", "кофе", "кава", "咖啡"),
    "cheese": _t("Käse", "fromage", "queso", "brânză", "сыр", "сир", "奶酪"),
    "cream": _t("Sahne", "crème", "nata", "smântână", "сливки", "вершки", "奶油"),
    "salad": _t("Salat", "salade", "ensalada", "salată", "салат", "салат", "沙拉"),
    "potato": _t("Kartoffel", "pomme de terre", "patata", "cartof", "картофель", "картопля", "土豆"),
    "potatoes": _t("Kartoffeln", "pommes de terre", "patatas", "cartofi", "картофель", "картопля", "土豆"),
    "butter": _t("Butter", "beurre", "mantequilla", "unt", "масло", "масло", "黄油"),
    "chocolate": _t("Schokolade", "chocolat", "chocolate", "ciocolată", "шоколад", "шоколад", "巧克力"),
    "banana": _t("Banane", "banane", "plátano", "banană", "банан", "банан", "香蕉"),
    "apple": _t("Apfel", "pomme", "manzana", "măr", "яблоко", "яблуко", "苹果"),
    "peanut": _t("Erdnuss", "cacahuète", "maní", "arahidă", "арахис", "арахіс", "花生"),
    "peanuts": _t("Erdnüsse", "cacahuètes", "maníes", "arahide", "арахис", "арахіс", "花生"),
    "smoothie": _t("Smoothie", "smoothie", "batido", "smoothie", "смузи", "смузі", "冰沙"),
    "breakfast": _t("Frühstück", "petit-déjeuner", "desayuno", "mic dejun", "завтрак", "сніданок", "早餐"),
    "turkey": _t("Pute", "dinde", "pavo", "curcan", "индейка", "індичка", "火鸡"),
    "green": _t("grün", "vert", "verde", "verde", "зелёный", "зелений", "绿"),
    "sausage": _t("Wurst", "saucisse", "salchicha", "cârnați", "колбаса", "ковбаса", "香肠"),
    "cereal": _t("Müsli", "céréales", "cereales", "cereale", "хлопья", "пластівці", "麦片"),
    "sandwich": _t("Sandwich", "sandwich", "sándwich", "sandwich", "сэндвич", "сендвіч", "三明治"),
    "bean": _t("Bohne", "haricot", "frijol", "fasole", "фасоль", "квасоля", "豆"),
    "beans": _t("Bohnen", "haricots", "frijoles", "fasole", "фасоль", "квасоля", "豆"),
    "soup": _t("Suppe", "soupe", "sopa", "supă", "суп", "суп", "汤"),
    "spinach": _t("Spinat", "épinards", "espinaca", "spanac", "шпинат", "шпинат", "菠菜"),
    "tea": _t("Tee", "thé", "té", "ceai", "чай", "чай", "茶"),
    "ice": _t("Eis", "glace", "hielo", "gheață", "лёд", "лід", "冰"),
    "thigh": _t("Keule", "cuisse", "muslo", "pulpă", "бедро", "стегно", "大腿"),
    "bacon": _t("Speck", "bacon", "beicon", "slănină", "бекон", "бекон", "培根"),
    "wheat": _t("Weizen", "blé", "trigo", "grâu", "пшеница", "пшениця", "小麦"),
    "cauliflower": _t("Blumenkohl", "chou-fleur", "coliflor", "conopidă", "цветная капуста", "цвітна капуста", "花椰菜"),
    "juice": _t("Saft", "jus", "zumo", "suc", "сок", "сік", "汁"),
    "yogurt": _t("Joghurt", "yaourt", "yogur", "iaurt", "йогурт", "йогурт", "酸奶"),
    "cookie": _t("Keks", "cookie", "galleta", "fursec", "печенье", "печиво", "曲奇"),
    "cookies": _t("Kekse", "cookies", "galletas", "fursecuri", "печенье", "печиво", "曲奇"),
    "biscuit": _t("Keks", "biscuit", "galleta", "biscuit", "печенье", "печиво", "饼干"),
    "biscuits": _t("Kekse", "biscuits", "galletas", "biscuiți", "печенье", "печиво", "饼干"),
    "toast": _t("Toast", "toast", "tostada", "toast", "тосты", "тости", "吐司"),
    "sugar": _t("Zucker", "sucre", "azúcar", "zahăr", "сахар", "цукор", "糖"),
    "bread": _t("Brot", "pain", "pan", "pâine", "хлеб", "хліб", "面包"),
    "wine": _t("Wein", "vin", "vino", "vin", "вино", "вино", "酒"),
    "strawberry": _t("Erdbeere", "fraise", "fresa", "căpșună", "клубника", "полуниця", "草莓"),
    "strawberries": _t("Erdbeeren", "fraises", "fresas", "căpșuni", "клубника", "полуниця", "草莓"),
    "pizza": _t("Pizza", "pizza", "pizza", "pizza", "пицца", "піца", "披萨"),
    "lemon": _t("Zitrone", "citron", "limón", "lămâie", "лимон", "лимон", "柠檬"),
    "onion": _t("Zwiebel", "oignon", "cebolla", "ceapă", "лук", "цибуля", "洋葱"),
    "onions": _t("Zwiebeln", "oignons", "cebollas", "cepe", "лук", "цибуля", "洋葱"),
    "egg": _t("Ei", "œuf", "huevo", "ou", "яйцо", "яйце", "鸡蛋"),
    "eggs": _t("Eier", "œufs", "huevos", "ouă", "яйца", "яйця", "鸡蛋"),
    "rice": _t("Reis", "riz", "arroz", "orez", "рис", "рис", "米饭"),
    "celery": _t("Sellerie", "céleri", "apio", "țelină", "сельдерей", "селера", "芹菜"),
    "honey": _t("Honig", "miel", "miel", "miere", "мёд", "мед", "蜂蜜"),
    "berry": _t("Beere", "baie", "baya", "boabă", "ягода", "ягода", "浆果"),
    "berries": _t("Beeren", "baies", "bayas", "fructe de pădure", "ягоды", "ягоди", "浆果"),
    "popcorn": _t("Popcorn", "pop-corn", "palomitas", "popcorn", "попкорн", "попкорн", "爆米花"),
    "orange": _t("Orange", "orange", "naranja", "portocală", "апельсин", "апельсин", "橙子"),
    "oranges": _t("Orangen", "oranges", "naranjas", "portocale", "апельсины", "апельсини", "橙子"),
    "chip": _t("Chip", "chip", "chip", "chips", "чипс", "чіп", "片"),
    "chips": _t("Chips", "chips", "chips", "chipsuri", "чипсы", "чіпси", "片"),
    "corn": _t("Mais", "maïs", "maíz", "porumb", "кукуруза", "кукурудза", "玉米"),
    "steak": _t("Steak", "steak", "bistec", "steak", "стейк", "стейк", "牛排"),
    "salmon": _t("Lachs", "saumon", "salmón", "somon", "лосось", "лосось", "三文鱼"),
    "lettuce": _t("Kopfsalat", "laitue", "lechuga", "salată verde", "салат-латук", "салат", "生菜"),
    "ranch": _t("Ranch", "ranch", "ranch", "ranch", "ранч", "ранч", "牧场酱"),
    "grape": _t("Traube", "raisin", "uva", "strugure", "виноград", "виноград", "葡萄"),
    "grapes": _t("Trauben", "raisins", "uvas", "struguri", "виноград", "виноград", "葡萄"),
    "oil": _t("Öl", "huile", "aceite", "ulei", "масло", "олія", "油"),
    "vinegar": _t("Essig", "vinaigre", "vinagre", "oțet", "уксус", "оцет", "醋"),
    "cranberry": _t("Cranberry", "canneberge", "arándano", "merișor", "клюква", "журавлина", "蔓越莓"),
    "cranberries": _t("Cranberries", "canneberges", "arándanos", "merișoare", "клюква", "журавлина", "蔓越莓"),
    "soda": _t("Limonade", "soda", "refresco", "suc carbogazos", "газировка", "газована вода", "汽水"),
    "cinnamon": _t("Zimt", "cannelle", "canela", "scorțișoară", "корица", "кориця", "肉桂"),
    "sauce": _t("Soße", "sauce", "salsa", "sos", "соус", "соус", "酱"),
    "pie": _t("Kuchen", "tarte", "tarta", "plăcintă", "пирог", "пиріг", "派"),
    "blueberry": _t("Heidelbeere", "myrtille", "arándano", "afină", "черника", "чорниця", "蓝莓"),
    "blueberries": _t("Heidelbeeren", "myrtilles", "arándanos", "afine", "черника", "чорниця", "蓝莓"),
    "oats": _t("Hafer", "avoine", "avena", "ovăz", "овёс", "овес", "燕麦"),
    "oatmeal": _t("Haferbrei", "flocons d'avoine", "avena", "ovăz", "овсянка", "вівсянка", "燕麦粥"),
    "avocado": _t("Avocado", "avocat", "aguacate", "avocado", "авокадо", "авокадо", "牛油果"),
    "tomato": _t("Tomate", "tomate", "tomate", "roșie", "помидор", "помідор", "番茄"),
    "tomatoes": _t("Tomaten", "tomates", "tomates", "roșii", "помидоры", "помідори", "番茄"),
    "shrimp": _t("Garnele", "crevette", "gamba", "crevete", "креветка", "креветка", "虾"),
    "broccoli": _t("Brokkoli", "brocoli", "brócoli", "broccoli", "брокколи", "броколі", "西兰花"),
    "cucumber": _t("Gurke", "concombre", "pepino", "castravete", "огурец", "огірок", "黄瓜"),
    "kale": _t("Grünkohl", "chou kale", "col rizada", "kale", "кале", "кале", "羽衣甘蓝"),
    "pepper": _t("Pfeffer", "poivre", "pimiento", "ardei", "перец", "перець", "椒"),
    "peppers": _t("Paprika", "poivrons", "pimientos", "ardei", "перцы", "перці", "椒"),
    "fruit": _t("Obst", "fruit", "fruta", "fruct", "фрукт", "фрукт", "水果"),
    "hamburger": _t("Hamburger", "hamburger", "hamburguesa", "hamburger", "гамбургер", "гамбургер", "汉堡"),
    "peach": _t("Pfirsich", "pêche", "melocotón", "piersică", "персик", "персик", "桃子"),
    "peaches": _t("Pfirsiche", "pêches", "melocotones", "piersici", "персики", "персики", "桃子"),
    "dressing": _t("Dressing", "vinaigrette", "aderezo", "dressing", "заправка", "заправка", "调味汁"),
    "tortilla": _t("Tortilla", "tortilla", "tortilla", "tortilla", "тортилья", "тортілья", "玉米饼"),
    "cheddar": _t("Cheddar", "cheddar", "cheddar", "cheddar", "чеддер", "чеддер", "切达"),
    "candy": _t("Süßigkeit", "bonbon", "caramelo", "bomboană", "конфета", "цукерка", "糖果"),
    "muffin": _t("Muffin", "muffin", "magdalena", "brioșă", "маффин", "мафін", "玛芬"),
    "muffins": _t("Muffins", "muffins", "magdalenas", "brioșe", "маффины", "мафіни", "玛芬"),
    "salsa": _t("Salsa", "salsa", "salsa", "salsa", "сальса", "сальса", "萨尔萨"),
    "breast": _t("Brust", "blanc", "pechuga", "piept", "грудка", "грудка", "胸"),
    "cherry": _t("Kirsche", "cerise", "cereza", "cireașă", "вишня", "вишня", "樱桃"),
    "bun": _t("Brötchen", "pain", "panecillo", "chiflă", "булочка", "булочка", "小圆面包"),
    "almond": _t("Mandel", "amande", "almendra", "migdală", "миндаль", "мигдаль", "杏仁"),
    "almonds": _t("Mandeln", "amandes", "almendras", "migdale", "миндаль", "мигдаль", "杏仁"),
    "pepperoni": _t("Pepperoni", "pepperoni", "pepperoni", "pepperoni", "пепперони", "пепероні", "意式辣肠"),
    "cake": _t("Kuchen", "gâteau", "pastel", "prăjitură", "торт", "торт", "蛋糕"),
    "fries": _t("Pommes", "frites", "patatas fritas", "cartofi prăjiți", "фри", "фрі", "薯条"),
    "taco": _t("Taco", "taco", "taco", "taco", "тако", "тако", "塔可"),
    "tacos": _t("Tacos", "tacos", "tacos", "taco-uri", "тако", "тако", "塔可"),
    "granola": _t("Granola", "granola", "granola", "granola", "гранола", "гранола", "格兰诺拉"),
    "chickpeas": _t("Kichererbsen", "pois chiches", "garbanzos", "năut", "нут", "нут", "鹰嘴豆"),
    "asparagus": _t("Spargel", "asperge", "espárragos", "sparanghel", "спаржа", "спаржа", "芦笋"),
    "roll": _t("Brötchen", "petit pain", "bollo", "chiflă", "булочка", "булочка", "卷"),
    "rolls": _t("Brötchen", "petits pains", "bollos", "chifle", "булочки", "булочки", "卷"),
    "syrup": _t("Sirup", "sirop", "sirope", "sirop", "сироп", "сироп", "糖浆"),
    "hummus": _t("Hummus", "houmous", "hummus", "hummus", "хумус", "хумус", "鹰嘴豆泥"),
    "pork": _t("Schweinefleisch", "porc", "cerdo", "porc", "свинина", "свинина", "猪肉"),
    "beer": _t("Bier", "bière", "cerveza", "bere", "пиво", "пиво", "啤酒"),
    "burrito": _t("Burrito", "burrito", "burrito", "burrito", "буррито", "буріто", "卷饼"),
    "burritos": _t("Burritos", "burritos", "burritos", "burrito-uri", "буррито", "буріто", "卷饼"),
    "maple": _t("Ahorn", "érable", "arce", "arțar", "клён", "клен", "枫"),
    "chili": _t("Chili", "chili", "chile", "chili", "чили", "чилі", "辣椒"),
    "fig": _t("Feige", "figue", "higo", "smochină", "инжир", "інжир", "无花果"),
    "pancake": _t("Pfannkuchen", "pancake", "tortita", "clătită", "блин", "млинець", "煎饼"),
    "cocoa": _t("Kakao", "cacao", "cacao", "cacao", "какао", "какао", "可可"),
    "ginger": _t("Ingwer", "gingembre", "jengibre", "ghimbir", "имбирь", "імбир", "姜"),
    "brownie": _t("Brownie", "brownie", "brownie", "brownie", "брауни", "брауні", "布朗尼"),
    "brownies": _t("Brownies", "brownies", "brownies", "brownie-uri", "брауни", "брауні", "布朗尼"),
    "mozzarella": _t("Mozzarella", "mozzarella", "mozzarella", "mozzarella", "моцарелла", "моцарела", "马苏里拉"),
    "carrot": _t("Karotte", "carotte", "zanahoria", "morcov", "морковь", "морква", "胡萝卜"),
    "carrots": _t("Karotten", "carottes", "zanahorias", "morcovi", "морковь", "морква", "胡萝卜"),
    "walnut": _t("Walnuss", "noix", "nuez", "nucă", "грецкий орех", "волоський горіх", "核桃"),
    "lamb": _t("Lamm", "agneau", "cordero", "miel", "баранина", "баранина", "羊肉"),
    "gyro": _t("Gyros", "gyro", "gyro", "gyros", "гирос", "гірос", "希腊烤肉"),
    "pecan": _t("Pekannuss", "pécan", "pacana", "nucă pecan", "пекан", "пекан", "山核桃"),
    "pecans": _t("Pekannüsse", "pécans", "pacanas", "nuci pecan", "пекан", "пекан", "山核桃"),
    "lasagna": _t("Lasagne", "lasagnes", "lasaña", "lasagna", "лазанья", "лазанья", "千层面"),
    "cashew": _t("Cashewnuss", "cajou", "anacardo", "caju", "кешью", "кеш'ю", "腰果"),
    "cashews": _t("Cashewnüsse", "cajous", "anacardos", "caju", "кешью", "кеш'ю", "腰果"),
    "duck": _t("Ente", "canard", "pato", "rață", "утка", "качка", "鸭"),
    "coconut": _t("Kokosnuss", "noix de coco", "coco", "cocos", "кокос", "кокос", "椰子"),
    "wrap": _t("Wrap", "wrap", "wrap", "wrap", "ролл", "рол", "卷饼"),
    "loaf": _t("Laib", "pain", "hogaza", "franzelă", "буханка", "буханець", "条"),
    "omelet": _t("Omelett", "omelette", "tortilla francesa", "omletă", "омлет", "омлет", "煎蛋卷"),
    "omelette": _t("Omelett", "omelette", "tortilla francesa", "omletă", "омлет", "омлет", "煎蛋卷"),
    "nuggets": _t("Nuggets", "nuggets", "nuggets", "nuggets", "наггетсы", "нагетси", "鸡块"),
    "cabbage": _t("Kohl", "chou", "repollo", "varză", "капуста", "капуста", "卷心菜"),
    "jerky": _t("Trockenfleisch", "viande séchée", "cecina", "jerky", "вяленое мясо", "в'ялене м'ясо", "肉干"),
    "water": _t("Wasser", "eau", "agua", "apă", "вода", "вода", "水"),
    "squash": _t("Kürbis", "courge", "calabaza", "dovleac", "тыква", "гарбуз", "南瓜"),
    "ziti": _t("Ziti", "ziti", "ziti", "ziti", "зити", "зіті", "通心粉"),
    "flour": _t("Mehl", "farine", "harina", "făină", "мука", "борошно", "面粉"),
    "fudge": _t("Fudge", "fudge", "fudge", "fudge", "фадж", "фадж", "软糖"),
    "raisin": _t("Rosine", "raisin sec", "pasa", "stafidă", "изюм", "родзинки", "葡萄干"),
    "raisins": _t("Rosinen", "raisins secs", "pasas", "stafide", "изюм", "родзинки", "葡萄干"),
    "cheesecake": _t("Käsekuchen", "cheesecake", "tarta de queso", "cheesecake", "чизкейк", "чизкейк", "芝士蛋糕"),
    "seafood": _t("Meeresfrüchte", "fruits de mer", "marisco", "fructe de mare", "морепродукты", "морепродукти", "海鲜"),
    "noodles": _t("Nudeln", "nouilles", "fideos", "tăiței", "лапша", "локшина", "面条"),
    "noodle": _t("Nudel", "nouille", "fideo", "tăiței", "лапша", "локшина", "面条"),
    "pineapple": _t("Ananas", "ananas", "piña", "ananas", "ананас", "ананас", "菠萝"),
    "vanilla": _t("Vanille", "vanille", "vainilla", "vanilie", "ваниль", "ваніль", "香草"),
    "coleslaw": _t("Krautsalat", "coleslaw", "ensalada de col", "salată de varză", "капустный салат", "салат з капусти", "凉拌卷心菜"),
    "slaw": _t("Krautsalat", "salade de chou", "ensalada de col", "salată de varză", "капустный салат", "салат з капусти", "凉拌卷心菜"),
    "grapefruit": _t("Grapefruit", "pamplemousse", "pomelo", "grepfrut", "грейпфрут", "грейпфрут", "葡萄柚"),
    "mushroom": _t("Pilz", "champignon", "champiñón", "ciupercă", "гриб", "гриб", "蘑菇"),
    "ravioli": _t("Ravioli", "ravioli", "ravioli", "ravioli", "равиоли", "равіолі", "馄饨"),
    "pasta": _t("Pasta", "pâtes", "pasta", "paste", "паста", "паста", "意面"),
    "tuna": _t("Thunfisch", "thon", "atún", "ton", "тунец", "тунець", "金枪鱼"),
    "salt": _t("Salz", "sel", "sal", "sare", "соль", "сіль", "盐"),
    "pistachio": _t("Pistazie", "pistache", "pistacho", "fistic", "фисташка", "фісташка", "开心果"),
    "pistachios": _t("Pistazien", "pistaches", "pistachos", "fistic", "фисташки", "фісташки", "开心果"),
    "pesto": _t("Pesto", "pesto", "pesto", "pesto", "песто", "песто", "青酱"),
    "kimchi": _t("Kimchi", "kimchi", "kimchi", "kimchi", "кимчи", "кімчі", "泡菜"),
    "salami": _t("Salami", "salami", "salami", "salam", "салями", "салямі", "萨拉米"),
    "sardines": _t("Sardinen", "sardines", "sardinas", "sardine", "сардины", "сардини", "沙丁鱼"),
    "anchovies": _t("Sardellen", "anchois", "anchoas", "hamsii", "анчоусы", "анчоуси", "凤尾鱼"),
    "olives": _t("Oliven", "olives", "aceitunas", "măsline", "оливки", "оливки", "橄榄"),
    "olive": _t("Olive", "olive", "aceituna", "măslină", "оливка", "оливка", "橄榄"),
    "garlic": _t("Knoblauch", "ail", "ajo", "usturoi", "чеснок", "часник", "大蒜"),
    "peas": _t("Erbsen", "petits pois", "guisantes", "mazăre", "горох", "горох", "豌豆"),
    "ham": _t("Schinken", "jambon", "jamón", "șuncă", "ветчина", "шинка", "火腿"),
    "beef": _t("Rindfleisch", "bœuf", "ternera", "vită", "говядина", "яловичина", "牛肉"),
    "fish": _t("Fisch", "poisson", "pescado", "pește", "рыба", "риба", "鱼"),
    "vegetable": _t("Gemüse", "légume", "verdura", "legumă", "овощ", "овоч", "蔬菜"),
    "vegetables": _t("Gemüse", "légumes", "verduras", "legume", "овощи", "овочі", "蔬菜"),
    "bagel": _t("Bagel", "bagel", "bagel", "bagel", "бейгл", "бейгл", "贝果"),
    "pita": _t("Pita", "pita", "pita", "lipie", "пита", "піта", "皮塔"),
    "waffle": _t("Waffel", "gaufre", "gofre", "vafe", "вафля", "вафля", "华夫饼"),
    "donut": _t("Donut", "donut", "dónut", "gogoașă", "пончик", "пончик", "甜甜圈"),
    "pretzel": _t("Brezel", "bretzel", "pretzel", "covrig", "крендель", "крендель", "椒盐卷饼"),
    "sushi": _t("Sushi", "sushi", "sushi", "sushi", "суши", "суші", "寿司"),
    "tilapia": _t("Tilapia", "tilapia", "tilapia", "tilapia", "тилапия", "тилапія", "罗非鱼"),
    "lemonade": _t("Limonade", "limonade", "limonada", "limonadă", "лимонад", "лимонад", "柠檬水"),
    "coke": _t("Cola", "coca", "coca", "cola", "кола", "кола", "可乐"),
    "cola": _t("Cola", "cola", "cola", "cola", "кола", "кола", "可乐"),
    "latte": _t("Latte", "latte", "latte", "latte", "латте", "лате", "拿铁"),
    "chai": _t("Chai", "chaï", "chai", "chai", "чай масала", "чай масала", "印度茶"),
    "mocha": _t("Mocha", "moka", "moca", "mocha", "мока", "мока", "摩卡"),
    "protein": _t("Protein", "protéine", "proteína", "proteină", "белок", "білок", "蛋白"),
    "bar": _t("Riegel", "barre", "barrita", "baton", "батончик", "батончик", "棒"),
    "shake": _t("Shake", "shake", "batido", "shake", "коктейль", "коктейль", "奶昔"),
    "cracker": _t("Cracker", "cracker", "galleta salada", "cracker", "крекер", "крекер", "苏打饼干"),
    "crackers": _t("Cracker", "crackers", "galletas saladas", "crackere", "крекеры", "крекери", "苏打饼干"),
    "nuts": _t("Nüsse", "noix", "frutos secos", "nuci", "орехи", "горіхи", "坚果"),
    "nut": _t("Nuss", "noix", "nuez", "nucă", "орех", "горіх", "坚果"),
    "leg": _t("Keule", "cuisse", "pierna", "pulpă", "ножка", "ніжка", "腿"),
    "wings": _t("Flügel", "ailes", "alitas", "aripi", "крылышки", "крильця", "翅"),
    "wing": _t("Flügel", "aile", "alita", "aripă", "крыло", "крило", "翅"),
    "rib": _t("Rippchen", "travers", "costilla", "coastă", "рёбрышко", "реберце", "排骨"),
    "ribs": _t("Rippchen", "travers", "costillas", "coaste", "рёбра", "ребра", "排骨"),
    "pear": _t("Birne", "poire", "pera", "pară", "груша", "груша", "梨"),
    "beet": _t("Rote Bete", "betterave", "remolacha", "sfeclă", "свёкла", "буряк", "甜菜"),
    "beets": _t("Rote Bete", "betteraves", "remolachas", "sfeclă", "свёкла", "буряк", "甜菜"),
    "clementine": _t("Clementine", "clémentine", "clementina", "clementină", "клементин", "клементин", "小柑橘"),
    "tangerine": _t("Mandarine", "mandarine", "mandarina", "mandarină", "мандарин", "мандарин", "橘子"),
    "mandarin": _t("Mandarine", "mandarine", "mandarina", "mandarină", "мандарин", "мандарин", "橘子"),
    "acai": _t("Açaí", "açaí", "açaí", "acai", "асаи", "асаї", "巴西莓"),
    "kombucha": _t("Kombucha", "kombucha", "kombucha", "kombucha", "комбуча", "комбуча", "康普茶"),
    "hummus": _t("Hummus", "houmous", "hummus", "hummus", "хумус", "хумус", "鹰嘴豆泥"),
    "quesadilla": _t("Quesadilla", "quesadilla", "quesadilla", "quesadilla", "кесадилья", "кесадилья", "墨西哥玉米饼"),
    "nachos": _t("Nachos", "nachos", "nachos", "nachos", "начос", "начос", "玉米片"),
    "enchiladas": _t("Enchiladas", "enchiladas", "enchiladas", "enchilada", "энчиладас", "енчіладас", "玉米卷"),
    "parmesan": _t("Parmesan", "parmesan", "parmesano", "parmezan", "пармезан", "пармезан", "帕玛森"),
    "swiss": _t("Schweizer Käse", "gruyère", "queso suizo", "cașcaval elvețian", "швейцарский сыр", "швейцарський сир", "瑞士奶酪"),
    "mozzarella": _t("Mozzarella", "mozzarella", "mozzarella", "mozzarella", "моцарелла", "моцарела", "马苏里拉"),
    "brie": _t("Brie", "brie", "brie", "brie", "бри", "брі", "布里"),
    "cheeseburger": _t("Cheeseburger", "cheeseburger", "hamburguesa con queso", "cheeseburger", "чизбургер", "чизбургер", "芝士汉堡"),
    "burger": _t("Burger", "burger", "hamburguesa", "burger", "бургер", "бургер", "汉堡"),
    "hotdog": _t("Hotdog", "hot-dog", "perrito caliente", "hot dog", "хот-дог", "хот-дог", "热狗"),
    "dog": _t("Würstchen", "saucisse", "perrito", "cârnat", "сосиска", "сосиска", "肠"),
    "grits": _t("Grits", "grits", "sémola", "mălai", "каша", "каша", "玉米粥"),
    "risotto": _t("Risotto", "risotto", "risotto", "risotto", "ризотто", "різото", "烩饭"),
    "barley": _t("Gerste", "orge", "cebada", "orz", "ячмень", "ячмінь", "大麦"),
    "stuffing": _t("Füllung", "farce", "relleno", "umplutură", "начинка", "начинка", "馅"),
    "dumpling": _t("Knödel", "boulette", "dumpling", "gălușcă", "пельмень", "пельмень", "饺子"),
    "cobbler": _t("Cobbler", "crumble", "crumble", "crumble", "коблер", "коблер", "水果酥"),
    "pudding": _t("Pudding", "pudding", "pudín", "budincă", "пудинг", "пудинг", "布丁"),
    "scone": _t("Scone", "scone", "scone", "scone", "скон", "скон", "司康"),
    "croissant": _t("Croissant", "croissant", "cruasán", "croissant", "круассан", "круасан", "可颂"),
    "croissants": _t("Croissants", "croissants", "cruasanes", "croissant-uri", "круассаны", "круасани", "可颂"),
    "margarine": _t("Margarine", "margarine", "margarina", "margarină", "маргарин", "маргарин", "人造黄油"),
    "jelly": _t("Gelee", "gelée", "jalea", "jeleu", "желе", "желе", "果酱"),
    "honey": _t("Honig", "miel", "miel", "miere", "мёд", "мед", "蜂蜜"),
    "stevia": _t("Stevia", "stévia", "estevia", "stevia", "стевия", "стевія", "甜叶菊"),
    "mayo": _t("Mayo", "mayo", "mayonesa", "maioneză", "майонез", "майонез", "蛋黄酱"),
    "mayonnaise": _t("Mayonnaise", "mayonnaise", "mayonesa", "maioneză", "майонез", "майонез", "蛋黄酱"),
    "mustard": _t("Senf", "moutarde", "mostaza", "muștar", "горчица", "гірчиця", "芥末"),
    "ketchup": _t("Ketchup", "ketchup", "kétchup", "ketchup", "кетчуп", "кетчуп", "番茄酱"),
    "barbecue": _t("Barbecue", "barbecue", "barbacoa", "grătar", "барбекю", "барбекю", "烧烤"),
    "bbq": _t("BBQ", "BBQ", "BBQ", "grătar", "барбекю", "барбекю", "烧烤"),
    "vinaigrette": _t("Vinaigrette", "vinaigrette", "vinagreta", "vinegretă", "винегрет", "вінегрет", "油醋汁"),
    "soy": _t("Soja", "soja", "soja", "soia", "соя", "соя", "大豆"),
    "tofu": _t("Tofu", "tofu", "tofu", "tofu", "тофу", "тофу", "豆腐"),
    "whey": _t("Molke", "lactosérum", "suero", "zer", "сыворотка", "сироватка", "乳清"),
    "flaxseed": _t("Leinsamen", "graine de lin", "linaza", "semințe de in", "льняное семя", "лляне насіння", "亚麻籽"),
    "flaxseeds": _t("Leinsamen", "graines de lin", "linaza", "semințe de in", "льняное семя", "лляне насіння", "亚麻籽"),
    "oats": _t("Hafer", "avoine", "avena", "ovăz", "овёс", "овес", "燕麦"),
    "greens": _t("Blattgemüse", "verts", "verdes", "verdețuri", "зелень", "зелень", "绿叶菜"),
    "mixed": _t("gemischt", "mélangé", "mixto", "amestecat", "смешанный", "змішаний", "混合"),
    "mix": _t("Mischung", "mélange", "mezcla", "amestec", "микс", "мікс", "混合"),
    "baked": _t("gebacken", "cuit au four", "al horno", "copt", "печёный", "печений", "烤"),
    "fried": _t("gebraten", "frit", "frito", "prăjit", "жареный", "смажений", "炸"),
    "grilled": _t("gegrillt", "grillé", "a la parrilla", "la grătar", "на гриле", "на грилі", "烤"),
    "steamed": _t("gedämpft", "vapeur", "al vapor", "fiert la abur", "на пару", "на парі", "蒸"),
    "boiled": _t("gekocht", "bouilli", "hervido", "fiert", "варёный", "варений", "煮"),
    "broiled": _t("gegrillt", "grillé", "asado", "gratinat", "запечённый", "запечений", "烤"),
    "roasted": _t("geröstet", "rôti", "asado", "prăjit", "жареный", "смажений", "烤"),
    "scrambled": _t("gerührt", "brouillé", "revuelto", "jumări", "болтунья", "бовтанка", "炒"),
    "frozen": _t("gefroren", "surgelé", "congelado", "congelat", "замороженный", "заморожений", "冷冻"),
    "homemade": _t("hausgemacht", "fait maison", "casero", "de casă", "домашний", "домашній", "自制"),
    "organic": _t("bio", "bio", "orgánico", "organic", "органический", "органічний", "有机"),
    "cooked": _t("gekocht", "cuit", "cocido", "gătit", "варёный", "варений", "熟"),
    "breaded": _t("paniert", "pané", "empanado", "pane", "в панировке", "в паніровці", "裹粉"),
    "stuffed": _t("gefüllt", "farci", "relleno", "umplut", "фаршированный", "фарширований", "酿"),
    "sliced": _t("geschnitten", "tranché", "en rodajas", "feliat", "нарезанный", "нарізаний", "切片"),
    "chopped": _t("gehackt", "haché", "picado", "tocat", "нарезанный", "нарізаний", "切碎"),
    "diced": _t("gewürfelt", "en dés", "en cubos", "cubulețe", "кубиками", "кубиками", "丁"),
    "mashed": _t("püriert", "en purée", "machacado", "piure", "пюре", "пюре", "泥"),
    "air": _t("Heißluft", "air fryer", "freidora de aire", "air fryer", "аэрогриль", "аерогриль", "空气炸"),
    "hard": _t("hart", "dur", "duro", "tare", "твёрдый", "твердий", "硬"),
    "small": _t("klein", "petit", "pequeño", "mic", "маленький", "маленький", "小"),
    "large": _t("groß", "grand", "grande", "mare", "большой", "великий", "大"),
    "medium": _t("mittel", "moyen", "mediano", "mediu", "средний", "середній", "中"),
    "plain": _t("natur", "nature", "natural", "simplu", "простой", "простий", "原味"),
    "spicy": _t("scharf", "épicé", "picante", "picant", "острый", "гострий", "辣"),
    "sweet": _t("süß", "sucré", "dulce", "dulce", "сладкий", "солодкий", "甜"),
    "salty": _t("salzig", "salé", "salado", "sărat", "солёный", "солоний", "咸"),
    "dark": _t("dunkel", "noir", "oscuro", "negru", "тёмный", "темний", "黑"),
    "white": _t("weiß", "blanc", "blanco", "alb", "белый", "білий", "白"),
    "red": _t("rot", "rouge", "rojo", "roșu", "красный", "червоний", "红"),
    "black": _t("schwarz", "noir", "negro", "negru", "чёрный", "чорний", "黑"),
    "yellow": _t("gelb", "jaune", "amarillo", "galben", "жёлтый", "жовтий", "黄"),
    "blue": _t("blau", "bleu", "azul", "albastru", "синий", "синій", "蓝"),
    "fresh": _t("frisch", "frais", "fresco", "proaspăt", "свежий", "свіжий", "新鲜"),
    "raw": _t("roh", "cru", "crudo", "crud", "сырой", "сирий", "生"),
    "low": _t("arm", "faible", "bajo", "scăzut", "низкий", "низький", "低"),
    "fat": _t("Fett", "matière grasse", "grasa", "grăsime", "жир", "жир", "脂肪"),
    "free": _t("frei", "sans", "sin", "fără", "без", "без", "无"),
    "diet": _t("Light", "light", "light", "dietetic", "диетический", "дієтичний", "无糖"),
    "decaf": _t("koffeinfrei", "décaféiné", "descafeinado", "decafeinizat", "без кофеина", "без кофеїну", "无咖啡因"),
    "skim": _t("magermilch", "écrémé", "desnatado", "degresat", "обезжиренный", "знежирений", "脱脂"),
    "skimmed": _t("entrahmt", "écrémé", "desnatado", "degresat", "обезжиренный", "знежирений", "脱脂"),
    "whole": _t("voll", "entier", "entero", "integral", "цельный", "цільний", "全脂"),
    "organic": _t("bio", "bio", "orgánico", "organic", "органический", "органічний", "有机"),
    "and": _t("und", "et", "y", "și", "и", "і", "和"),
    "with": _t("mit", "avec", "con", "cu", "с", "з", "加"),
    "of": _t("von", "de", "de", "de", "из", "з", "的"),
    "or": _t("oder", "ou", "o", "sau", "или", "або", "或"),
    "without": _t("ohne", "sans", "sin", "fără", "без", "без", "不含"),
    "from": _t("von", "de", "de", "de la", "из", "з", "来自"),
    "cottage": _t("Hüttenkäse", "fromage blanc", "requesón", "brânză de vaci", "творог", "сир кисломолочний", "cottage"),
    "caesar": _t("Caesar", "césar", "césar", "caesar", "цезарь", "цезар", "凯撒"),
    "sweetener": _t("Süßstoff", "édulcorant", "edulcorante", "îndulcitor", "подсластитель", "підсолоджувач", "甜味剂"),
    "mountain": _t("Berg", "montagne", "montaña", "munte", "гора", "гора", "山"),
    "ground": _t("Hack", "haché", "picada", "tocată", "фарш", "фарш", "末"),
    "peppermint": _t("Pfefferminz", "menthe poivrée", "menta piperita", "mentă", "перечная мята", "перцева м'ята", "薄荷"),
    "caramel": _t("Karamell", "caramel", "caramelo", "caramel", "карамель", "карамель", "焦糖"),
    "english": _t("englisch", "anglais", "inglés", "englezesc", "английский", "англійський", "英式"),
    "drink": _t("Getränk", "boisson", "bebida", "băutură", "напиток", "напій", "饮料"),
    "bell": _t("Paprika", "poivron", "pimiento", "ardei", "перец", "перець", "甜椒"),
    "hot": _t("scharf", "épicé", "picante", "iute", "острый", "гострий", "辣"),
    "thins": _t("Thins", "thins", "thins", "thins", "тонкие", "тонкі", "薄片"),
    "pop": _t("Pop", "pop", "pop", "pop", "поп", "поп", "爆"),
    "toffee": _t("Toffee", "caramel mou", "toffee", "toffee", "ириска", "іриска", "太妃糖"),
    "bark": _t("Schokoladenbruch", "écorce de chocolat", "corteza de chocolate", "scoarță de ciocolată", "шоколадная кора", "шоколадна кора", "巧克力碎"),
    "bowl": _t("Schüssel", "bol", "tazón", "bol", "миска", "миска", "碗"),
    "multigrain": _t("Mehrkorn", "multicéréales", "multigrano", "multicereale", "мультизлаковый", "мультизлаковий", "多谷"),
    "stock": _t("Brühe", "bouillon", "caldo", "supă", "бульон", "бульйон", "高汤"),
    "stick": _t("Stange", "bâtonnet", "palito", "băț", "палочка", "паличка", "条"),
    "sticks": _t("Stangen", "bâtonnets", "palitos", "bețe", "палочки", "палички", "条"),
    "raspberry": _t("Himbeere", "framboise", "frambuesa", "zmeură", "малина", "малина", "覆盆子"),
    "brown": _t("braun", "brun", "marrón", "maro", "коричневый", "коричневий", "棕"),
    "lactose": _t("laktosefrei", "sans lactose", "sin lactosa", "fără lactoză", "безлактозный", "безлактозний", "无乳糖"),
    "lightly": _t("leicht", "légèrement", "ligeramente", "ușor", "слегка", "злегка", "轻度"),
    "salted": _t("gesalzen", "salé", "salado", "sărat", "солёный", "солоний", "咸"),
    "chunk": _t("Stück", "morceau", "trozo", "bucată", "кусок", "шматок", "块"),
    "snack": _t("Snack", "encas", "tentempié", "gustare", "снек", "снек", "零食"),
    "light": _t("light", "light", "light", "light", "лайт", "лайт", "低糖"),
    "bourbon": _t("Bourbon", "bourbon", "bourbon", "bourbon", "бурбон", "бурбон", "波本"),
    "dew": _t("Dew", "Dew", "Dew", "Dew", "Dew", "Dew", "Dew"),
    "lean": _t("mager", "maigre", "magro", "slab", "постный", "пісний", "瘦"),
    "italian": _t("italienisch", "italien", "italiano", "italian", "итальянский", "італійський", "意式"),
    "strips": _t("Streifen", "lamelles", "tiras", "fâșii", "полоски", "смужки", "条"),
    "strip": _t("Streifen", "lamelle", "tira", "fâșie", "полоска", "смужка", "条"),
    "mint": _t("Minze", "menthe", "menta", "mentă", "мята", "м'ята", "薄荷"),
    "mints": _t("Minzbonbons", "menthes", "mentas", "bombe de mentă", "мятные конфеты", "м'ятні цукерки", "薄荷糖"),
    "mac": _t("Mac", "mac", "mac", "mac", "мак", "мак", "通心粉"),
    "old": _t("alt", "vieux", "viejo", "vechi", "старый", "старий", "老"),
    "cobb": _t("Cobb", "cobb", "cobb", "cobb", "кобб", "кобб", "科布"),
    "grill": _t("Grill", "grill", "parrilla", "grătar", "гриль", "гриль", "烤架"),
    "navel": _t("Navel", "navel", "navel", "navel", "пупочный", "пупковий", "脐橙"),
    "seedless": _t("kernlos", "sans pépins", "sin semillas", "fără sâmburi", "без косточек", "без кісточок", "无籽"),
    "french": _t("französisch", "français", "francés", "francez", "французский", "французький", "法式"),
    "sub": _t("Sub", "sub", "sub", "sub", "саб", "саб", "潜艇堡"),
    "biscotti": _t("Cantuccini", "biscotti", "biscotti", "biscotti", "бискотти", "біскотті", "意式饼干"),
    "pieces": _t("Stücke", "morceaux", "trozos", "bucăți", "кусочки", "шматочки", "块"),
    "bite": _t("Happen", "bouchée", "bocado", "îmbucătură", "кусочек", "шматочок", "一口"),
    "bites": _t("Happen", "bouchées", "bocados", "îmbucături", "кусочки", "шматочки", "小块"),
    "heavy": _t("sahne", "épaisse", "espesa", "groasă", "жирные", "жирні", "浓"),
    "puffs": _t("Puffs", "soufflés", "puffs", "puffs", "паффы", "пафи", "泡芙"),
    "rings": _t("Ringe", "anneaux", "aros", "inele", "кольца", "кільця", "圈"),
    "broth": _t("Brühe", "bouillon", "caldo", "supă", "бульон", "бульйон", "汤"),
    "gin": _t("Gin", "gin", "gin", "gin", "джин", "джин", "金酒"),
    "soaked": _t("eingeweicht", "trempé", "remojado", "înmuiat", "замоченный", "замочений", "浸泡"),
    "trail": _t("Studentenfutter", "mélange", "mix", "mix", "смесь", "суміш", "什锦"),
    "crunch": _t("Crunch", "crunch", "crujiente", "crocant", "хрустящий", "хрусткий", "脆"),
    "original": _t("Original", "original", "original", "original", "оригинальный", "оригінальний", "原味"),
    "balls": _t("Kugeln", "boules", "bolas", "bile", "шарики", "кульки", "球"),
    "wafers": _t("Waffeln", "gaufrettes", "obleas", "napolitane", "вафли", "вафлі", "威化"),
    "vodka": _t("Wodka", "vodka", "vodka", "vodcă", "водка", "горілка", "伏特加"),
    "fashioned": _t("klassisch", "à l'ancienne", "tradicional", "clasic", "классический", "класичний", "传统"),
    "candies": _t("Bonbons", "bonbons", "caramelos", "bomboane", "конфеты", "цукерки", "糖果"),
    "mash": _t("Püree", "purée", "puré", "piure", "пюре", "пюре", "泥"),
    "crabcake": _t("Krabbenküchlein", "galette de crabe", "tortita de cangrejo", "chiftea de crab", "крабовая котлета", "крабова котлета", "蟹饼"),
    "oven": _t("Ofen", "four", "horno", "cuptor", "духовка", "духовка", "烤箱"),
    "crust": _t("Kruste", "croûte", "corteza", "crustă", "корка", "скоринка", "皮"),
    "crunchy": _t("knusprig", "croquant", "crujiente", "crocant", "хрустящий", "хрусткий", "脆"),
    "veggie": _t("Gemüse", "légume", "verdura", "legumă", "овощной", "овочевий", "蔬菜"),
    "blend": _t("Mischung", "mélange", "mezcla", "amestec", "смесь", "суміш", "混合"),
    "farm": _t("Hof", "ferme", "granja", "fermă", "ферма", "ферма", "农场"),
    "cakes": _t("Kuchen", "gâteaux", "pasteles", "prăjituri", "торты", "торти", "蛋糕"),
    "salisbury": _t("Salisbury", "salisbury", "salisbury", "salisbury", "солсбери", "солсбері", "索尔兹伯里"),
    "delicious": _t("Delicious", "delicious", "delicious", "delicious", "делишес", "делішес", "蛇果"),
    "southwest": _t("Südwest", "sud-ouest", "suroeste", "sud-vest", "юго-западный", "південно-західний", "西南"),
    "slim": _t("slim", "slim", "slim", "slim", "слим", "слім", "低脂"),
    "side": _t("Beilage", "accompagnement", "acompañamiento", "garnitură", "гарнир", "гарнір", "配菜"),
    "macaroni": _t("Makkaroni", "macaroni", "macarrones", "macaroane", "макароны", "макарони", "通心粉"),
    "spring": _t("Frühling", "printemps", "primavera", "primăvară", "весенний", "весняний", "春"),
    "classic": _t("klassisch", "classique", "clásico", "clasic", "классический", "класичний", "经典"),
    "roast": _t("Braten", "rôti", "asado", "friptură", "жаркое", "печеня", "烤"),
    "vienna": _t("Wiener", "viennois", "vienés", "vienez", "венский", "віденський", "维也纳"),
    "bars": _t("Riegel", "barres", "barritas", "batonase", "батончики", "батончики", "棒"),
    "buttered": _t("mit Butter", "beurré", "con mantequilla", "cu unt", "с маслом", "з маслом", "黄油"),
    "refried": _t("refried", "refritos", "refritos", "prăjită", "жареная", "смажена", "再炸"),
    "stew": _t("Eintopf", "ragoût", "estofado", "tocană", "рагу", "рагу", "炖"),
    "curd": _t("Quark", "caillé", "cuajada", "caș", "творог", "сир", "凝乳"),
    "curds": _t("Quark", "caillé", "cuajada", "caș", "творог", "сир", "凝乳"),
    "chorizo": _t("Chorizo", "chorizo", "chorizo", "chorizo", "чоризо", "чоризо", "西班牙肠"),
    "slider": _t("Mini-Burger", "mini-burger", "slider", "mini-burger", "слайдер", "слайдер", "迷你汉堡"),
    "partly": _t("teilweise", "partiellement", "parcialmente", "parțial", "частично", "частково", "部分"),
    "cup": _t("Tasse", "tasse", "taza", "cană", "чашка", "чашка", "杯"),
    "cups": _t("Tassen", "tasses", "tazas", "căni", "чашки", "чашки", "杯"),
    "chewy": _t("zäh", "moelleux", "masticable", "moale", "жевательный", "жувальний", "有嚼劲"),
    "club": _t("Club", "club", "club", "club", "клаб", "клаб", "俱乐部"),
    "double": _t("doppelt", "double", "doble", "dublu", "двойной", "подвійний", "双层"),
    "pack": _t("Packung", "paquet", "paquete", "pachet", "пачка", "пачка", "包"),
    "smoke": _t("geräuchert", "fumé", "ahumado", "afumat", "копчёный", "копчений", "烟熏"),
    "house": _t("Haus", "maison", "casa", "casă", "домашний", "домашній", "招牌"),
    "frosted": _t("glasiert", "glacé", "glaseado", "glazurat", "глазированный", "глазурований", "糖霜"),
    "flake": _t("Flocke", "flocon", "copo", "fulg", "хлопь", "пластівець", "片"),
    "blt": _t("BLT", "BLT", "BLT", "BLT", "BLT", "BLT", "BLT"),
    "harvest": _t("Ernte", "récolte", "cosecha", "recoltă", "урожай", "урожай", "收获"),
    "cannoli": _t("Cannoli", "cannoli", "cannoli", "cannoli", "канноли", "канолі", "奶油卷"),
    "cotton": _t("Zuckerwatte", "barbe à papa", "algodón de azúcar", "vată de zahăr", "сахарная вата", "цукрова вата", "棉花糖"),
    "moscato": _t("Moscato", "muscat", "moscato", "moscato", "москато", "москато", "莫斯卡托"),
    "popped": _t("gepoppt", "éclaté", "reventado", "popcorn", "воздушный", "попкорн", "爆"),
    "tzatziki": _t("Tzatziki", "tzatziki", "tzatziki", "tzatziki", "дзадзики", "дзадзикі", "希腊酸奶酱"),
    "baby": _t("Baby", "baby", "baby", "baby", "мини", "міні", "小"),
    "tender": _t("zart", "tendre", "tierno", "fraged", "нежный", "ніжний", "嫩"),
    "shell": _t("Schale", "coquille", "cáscara", "coajă", "скорлупа", "шкаралупа", "壳"),
    "shells": _t("Muschelnudeln", "coquilles", "conchas", "scoici", "ракушки", "мушлі", "贝壳面"),
    "everything": _t("Everything", "everything", "everything", "everything", "everything", "everything", "全能"),
    "spanish": _t("spanisch", "espagnol", "español", "spaniol", "испанский", "іспанський", "西班牙"),
    "velvet": _t("Velvet", "velvet", "velvet", "velvet", "вельвет", "вельвет", "天鹅绒"),
    "chardonnay": _t("Chardonnay", "chardonnay", "chardonnay", "chardonnay", "шардоне", "шардоне", "霞多丽"),
    "powder": _t("Pulver", "poudre", "polvo", "pudră", "порошок", "порошок", "粉"),
    "caesar": _t("Caesar", "césar", "césar", "caesar", "цезарь", "цезар", "凯撒"),
    "meal": _t("Mahlzeit", "repas", "comida", "masă", "еда", "їжа", "餐"),
    "thin": _t("dünn", "fin", "fino", "subțire", "тонкий", "тонкий", "薄"),
    "summer": _t("Sommer", "été", "verano", "vară", "летний", "літній", "夏"),
    "blackberries": _t("Brombeeren", "mûres", "moras", "mure", "ежевика", "ожина", "黑莓"),
    "sloppy": _t("Sloppy", "sloppy", "sloppy", "sloppy", "слоппи", "слоппі", "斯洛比"),
    "dough": _t("Teig", "pâte", "masa", "aluat", "тесто", "тісто", "面团"),
    "dijonnaise": _t("Dijonnaise", "dijonnaise", "dijonesa", "dijoneză", "дижонез", "дижонез", "第戎酱"),
    "canned": _t("aus der Dose", "en conserve", "en lata", "din conservă", "консервированный", "консервований", "罐装"),
    "riced": _t("gerieselt", "en grains", "en granos", "mărunțit", "дроблёный", "подрібнений", "碎"),
    "gummies": _t("Gummibonbons", "bonbons gélifiés", "gominolas", "jeleuri", "мармелад", "мармелад", "软糖"),
    "wild": _t("wild", "sauvage", "silvestre", "sălbatic", "дикий", "дикий", "野生"),
    "soft": _t("weich", "moelleux", "suave", "moale", "мягкий", "м'який", "软"),
    "herbal": _t("Kräuter", "aux herbes", "de hierbas", "din plante", "травяной", "трав'яний", "草本"),
    "instant": _t("Instant", "instantané", "instantáneo", "instant", "быстрый", "швидкий", "速食"),
    "thousand": _t("tausend", "mille", "mil", "o mie", "тысяча", "тисяча", "千"),
    "island": _t("Insel", "île", "isla", "insulă", "остров", "острів", "岛"),
    "pepperjack": _t("Pepper Jack", "pepper jack", "pepper jack", "pepper jack", "пеппер джек", "пепер джек", "胡椒杰克"),
    "creamer": _t("Kaffeeweißer", "crème à café", "crema", "smântână de cafea", "сливки", "вершки", "奶精"),
    "traditional": _t("traditionell", "traditionnel", "tradicional", "tradițional", "традиционный", "традиційний", "传统"),
    "sport": _t("Sport", "sport", "deporte", "sport", "спортивный", "спортивний", "运动"),
    "single": _t("einzeln", "simple", "sencillo", "simplu", "один", "один", "单"),
    "serving": _t("Portion", "portion", "ración", "porție", "порция", "порція", "份"),
    "natural": _t("natur", "naturel", "natural", "natural", "натуральный", "натуральний", "天然"),
    "panko": _t("Panko", "panko", "panko", "panko", "панко", "панко", "面包糠"),
    "punch": _t("Bowle", "punch", "ponche", "punch", "пунш", "пунш", "潘趣"),
    "pink": _t("rosa", "rose", "rosa", "roz", "розовый", "рожевий", "粉"),
    "extra": _t("extra", "extra", "extra", "extra", "экстра", "екстра", "特浓"),
    "sandwiches": _t("Sandwiches", "sandwichs", "sándwiches", "sandwich-uri", "сэндвичи", "сендвічі", "三明治"),
    "southern": _t("südlich", "du sud", "sureño", "sudic", "южный", "південний", "南方"),
    "style": _t("Art", "style", "estilo", "stil", "стиль", "стиль", "风味"),
    "supreme": _t("Supreme", "suprême", "supreme", "supreme", "суприм", "супрім", "至尊"),
    "malted": _t("Malz", "malté", "malteado", "cu malț", "солодовый", "солодовий", "麦芽"),
    "deluxe": _t("Deluxe", "deluxe", "deluxe", "deluxe", "делюкс", "делюкс", "豪华"),
    "boneless": _t("ohne Knochen", "désossé", "sin hueso", "fără os", "без костей", "без кісток", "去骨"),
    "skinless": _t("ohne Haut", "sans peau", "sin piel", "fără piele", "без кожи", "без шкіри", "去皮"),
    "skinny": _t("light", "light", "light", "light", "лёгкий", "легкий", "低卡"),
    "kettle": _t("Kettle", "chaudron", "kettle", "kettle", "котёл", "казан", "锅炒"),
    "angel": _t("Engel", "ange", "ángel", "înger", "ангел", "ангел", "天使"),
    "loin": _t("Lende", "longe", "lomo", "mușchi", "вырезка", "вирізка", "里脊"),
    "tenderloin": _t("Filet", "filet", "solomillo", "mușchi file", "вырезка", "вирізка", "里脊"),
    "beers": _t("Biere", "bières", "cervezas", "beri", "пиво", "пиво", "啤酒"),
    "topping": _t("Belag", "garniture", "cobertura", "topping", "топпинг", "топінг", "浇头"),
    "dried": _t("getrocknet", "séché", "seco", "uscat", "сушёный", "сушений", "干"),
    "twists": _t("Twists", "torsades", "twists", "răsucite", "скрутки", "скрутки", "扭条"),
    "birthday": _t("Geburtstag", "anniversaire", "cumpleaños", "zi de naștere", "день рождения", "день народження", "生日"),
    "seasoned": _t("gewürzt", "assaisonné", "sazonado", "condimentat", "приправленный", "приправлений", "调味"),
    "porkchop": _t("Schweinekotelett", "côte de porc", "chuleta de cerdo", "cotlet de porc", "свиная отбивная", "свиняча відбивна", "猪排"),
    "mini": _t("Mini", "mini", "mini", "mini", "мини", "міні", "迷你"),
    "nutty": _t("nussig", "noisette", "nueces", "cu nuci", "ореховый", "горіховий", "坚果"),
    "mojito": _t("Mojito", "mojito", "mojito", "mojito", "мохито", "мохіто", "莫吉托"),
    "casserole": _t("Auflauf", "gratin", "cazuela", "budincă sărată", "запеканка", "запіканка", "砂锅"),
    "garden": _t("Garten", "jardin", "jardín", "grădină", "садовый", "садовий", "田园"),
    "gravy": _t("Soße", "sauce", "salsa", "sos", "подливка", "підлива", "肉汁"),
    "greek": _t("griechisch", "grec", "griego", "grecesc", "греческий", "грецький", "希腊"),
    "crumbs": _t("Brösel", "miettes", "migas", "fărâmituri", "крошки", "крихти", "屑"),
    "nonfat": _t("fettfrei", "sans matière grasse", "sin grasa", "degresat", "обезжиренный", "знежирений", "脱脂"),
    "pound": _t("Pfund", "livre", "libra", "livră", "фунт", "фунт", "磅"),
    "tater": _t("Kartoffel", "patate", "papa", "cartof", "картофель", "картопля", "土豆"),
    "tots": _t("Kroketten", "croquettes", "croquetas", "crochete", "крокеты", "крокети", "薯球"),
    "golden": _t("golden", "doré", "dorado", "auriu", "золотой", "золотий", "金"),
    "leftover": _t("Reste", "reste", "sobras", "resturi", "остатки", "залишки", "剩菜"),
    "bag": _t("Tüte", "sachet", "bolsa", "pungă", "пакет", "пакет", "袋"),
    "box": _t("Schachtel", "boîte", "caja", "cutie", "коробка", "коробка", "盒"),
    "size": _t("Größe", "taille", "tamaño", "mărime", "размер", "розмір", "份量"),
    "food": _t("Essen", "aliment", "comida", "mâncare", "еда", "їжа", "食物"),
    "foods": _t("Lebensmittel", "aliments", "alimentos", "alimente", "продукты", "продукти", "食品"),
    "home": _t("Haus", "maison", "casa", "casă", "домашний", "домашній", "家"),
    "skin": _t("Schale", "peau", "piel", "coajă", "кожура", "шкірка", "皮"),
    "boost": _t("Boost", "boost", "boost", "boost", "буст", "буст", "增强"),
    "plus": _t("Plus", "plus", "plus", "plus", "плюс", "плюс", "加"),
    "zero": _t("Zero", "zéro", "cero", "zero", "ноль", "нуль", "零"),
    "order": _t("Portion", "commande", "orden", "porție", "заказ", "замовлення", "份"),
    "helper": _t("Helper", "helper", "helper", "helper", "хелпер", "хелпер", "帮手"),
    "rise": _t("Rise", "rise", "rise", "rise", "райз", "райз", "起"),
    "special": _t("speziell", "spécial", "especial", "special", "особый", "особливий", "特制"),
    "smart": _t("Smart", "smart", "smart", "smart", "смарт", "смарт", "智慧"),
    "balance": _t("Balance", "équilibre", "equilibrio", "echilibru", "баланс", "баланс", "平衡"),
    "wingettes": _t("Flügelstücke", "ailerons", "alitas", "aripioare", "крылышки", "крильця", "翅中"),
    "bunny": _t("Hase", "lapin", "conejo", "iepure", "зайчик", "зайчик", "兔子"),
    "triangles": _t("Dreiecke", "triangles", "triángulos", "triunghiuri", "треугольники", "трикутники", "三角"),
    "cara": _t("Cara Cara", "Cara Cara", "Cara Cara", "Cara Cara", "Cara Cara", "Cara Cara", "卡拉"),
    "cuties": _t("Mandarinen", "clémentines", "mandarinas", "clementine", "мандарины", "мандарини", "小柑橘"),
    "cornflakes": _t("Cornflakes", "corn-flakes", "copos de maíz", "fulgi de porumb", "кукурузные хлопья", "кукурудзяні пластівці", "玉米片"),
    "nutrigrain": _t("Nutri-Grain", "Nutri-Grain", "Nutri-Grain", "Nutri-Grain", "Nutri-Grain", "Nutri-Grain", "Nutri-Grain"),
    "krispies": _t("Krispies", "krispies", "krispies", "krispies", "криспис", "кріспіс", "脆米"),
    "creamers": _t("Kaffeeweißer", "crèmes à café", "cremas", "smântână de cafea", "сливки", "вершки", "奶精"),
    "creams": _t("Cremes", "crèmes", "cremas", "creme", "кремы", "креми", "奶油"),
    "wavy": _t("wellig", "ondulé", "ondulado", "ondulat", "волнистый", "хвилястий", "波浪"),
    "crostinis": _t("Crostini", "crostini", "crostini", "crostini", "кростини", "кростіні", "烤面包片"),
    "beurre": _t("Butter", "beurre", "mantequilla", "unt", "масло", "масло", "黄油"),
    "petit": _t("klein", "petit", "pequeño", "mic", "маленький", "маленький", "小"),
    "brick": _t("Ziegel", "brique", "ladrillo", "cărămidă", "кирпич", "цегла", "砖"),
    "pot": _t("Topf", "pot", "olla", "oală", "горшок", "горщик", "锅"),
    "ultra": _t("Ultra", "ultra", "ultra", "ultra", "ультра", "ультра", "超"),
    "fierce": _t("Fierce", "fierce", "fierce", "fierce", "ферс", "ферс", "强劲"),
    "cosmic": _t("kosmisch", "cosmique", "cósmico", "cosmic", "космический", "космічний", "宇宙"),
    "aussie": _t("australisch", "australien", "australiano", "australian", "австралийский", "австралійський", "澳式"),
    "choc": _t("Schoko", "choco", "choco", "cioco", "шок", "шок", "巧"),
    "go": _t("Go", "go", "go", "go", "го", "го", "Go"),
}

WORD_ALIASES: dict[str, str] = {
    "cottge": "cottage",
    "moutain": "mountain",
    "cinammon": "cinnamon",
    "sandwhich": "sandwich",
    "sweetner": "sweetener",
    "vinegrette": "vinaigrette",
    "cesear": "caesar",
    "buttter": "butter",
    "slcie": "slice",
    "mozarrella": "mozzarella",
    "gnd": "ground",
    "pc": "piece",
    "bfast": "breakfast",
    "pb": "peanut",
    "tatziki": "tzatziki",
    "cannolli": "cannoli",
    "biscott": "biscotti",
    "caracara": "cara",
    "choc": "chocolate",
}

UNITS: dict[str, dict[str, str]] = {
    "cup": _t("Tasse", "tasse", "taza", "cană", "чашка", "чашка", "杯"),
    "cups": _t("Tassen", "tasses", "tazas", "căni", "чашки", "чашки", "杯"),
    "fluid ounce": _t("Flüssigunze", "once liquide", "onza líquida", "uncie lichidă", "жидкая унция", "рідка унція", "液量盎司"),
    "ounce": _t("Unze", "once", "onza", "uncie", "унция", "унція", "盎司"),
    "tbsp": _t("EL", "c. à s.", "cda", "lingură", "ст. л.", "ст. л.", "汤匙"),
    "tablespoon": _t("Esslöffel", "cuillère à soupe", "cucharada", "lingură", "ст. л.", "ст. л.", "汤匙"),
    "tsp": _t("TL", "c. à c.", "cdta", "linguriță", "ч. л.", "ч. л.", "茶匙"),
    "teaspoon": _t("Teelöffel", "cuillère à café", "cucharadita", "linguriță", "ч. л.", "ч. л.", "茶匙"),
    "g": _t("g", "g", "g", "g", "г", "г", "克"),
    "gram": _t("Gramm", "gramme", "gramo", "gram", "грамм", "грам", "克"),
    "grams": _t("Gramm", "grammes", "gramos", "grame", "грамм", "грам", "克"),
    "ml": _t("ml", "ml", "ml", "ml", "мл", "мл", "毫升"),
    "piece": _t("Stück", "pièce", "pieza", "bucată", "штука", "штука", "块"),
    "pieces": _t("Stück", "pièces", "piezas", "bucăți", "штуки", "штуки", "块"),
    "serving": _t("Portion", "portion", "ración", "porție", "порция", "порція", "份"),
    "servings": _t("Portionen", "portions", "raciones", "porții", "порции", "порції", "份"),
    "slice": _t("Scheibe", "tranche", "rebanada", "felie", "ломтик", "скибка", "片"),
    "slices": _t("Scheiben", "tranches", "rebanadas", "felii", "ломтики", "скибки", "片"),
    "bowl": _t("Schüssel", "bol", "tazón", "bol", "миска", "миска", "碗"),
    "can": _t("Dose", "boîte", "lata", "conservă", "банка", "банка", "罐"),
    "bag": _t("Tüte", "sachet", "bolsa", "pungă", "пакет", "пакет", "袋"),
    "pack": _t("Packung", "paquet", "paquete", "pachet", "пачка", "пачка", "包"),
    "bar": _t("Riegel", "barre", "barrita", "baton", "батончик", "батончик", "棒"),
    "scoop": _t("Kugel", "cuillère", "cucharada", "lingură", "ложка", "ложка", "勺"),
    "stick": _t("Stange", "bâtonnet", "palito", "băț", "палочка", "паличка", "条"),
    "stalks": _t("Stangen", "tiges", "tallos", "tulpini", "стебли", "стебла", "茎"),
    "pint": _t("Pint", "pinte", "pinta", "halbă", "пинта", "пинта", "品脱"),
    "lb": _t("Pfund", "livre", "libra", "livră", "фунт", "фунт", "磅"),
    "egg": _t("Ei", "œuf", "huevo", "ou", "яйцо", "яйце", "个蛋"),
    "eggs": _t("Eier", "œufs", "huevos", "ouă", "яйца", "яйця", "个蛋"),
    "muffin": _t("Muffin", "muffin", "magdalena", "brioșă", "маффин", "мафін", "个玛芬"),
    "muffins": _t("Muffins", "muffins", "magdalenas", "brioșe", "маффины", "мафіни", "个玛芬"),
    "cookie": _t("Keks", "cookie", "galleta", "fursec", "печенье", "печиво", "块曲奇"),
    "sandwich": _t("Sandwich", "sandwich", "sándwich", "sandwich", "сэндвич", "сендвіч", "个三明治"),
    "scone": _t("Scone", "scone", "scone", "scone", "скон", "скон", "个司康"),
    "omelet": _t("Omelett", "omelette", "tortilla", "omletă", "омлет", "омлет", "个蛋饼"),
    "crackers": _t("Cracker", "crackers", "galletas", "crackere", "крекеры", "крекери", "片饼干"),
}

UNIT_ALIASES: dict[str, str] = {
    "tablespoons": "tablespoon",
    "teaspoons": "teaspoon",
    "fluid ounces": "fluid ounce",
    "fluid oz": "fluid ounce",
    "fl oz": "fluid ounce",
    "fl. oz.": "fluid ounce",
    "fl. oz": "fluid ounce",
    "oz": "ounce",
    "ounces": "ounce",
    "tbsp": "tbsp",
    "pckg": "pack",
    "slcie": "slice",
}
