"""bg / ja / ko names for each catalog capital (rank-0 city).

Merged into ``CITY_I18N`` so a Japanese/Korean/Bulgarian suggestion is
either fully local (``ベルリン, ドイツ``) or fully English — never mixed.
"""
from __future__ import annotations

from typing import Final

# (English city, English country) -> {bg, ja, ko}
CAPITAL_I18N: Final[dict[tuple[str, str], dict[str, str]]] = {
    ("Kabul", "Afghanistan"): {"bg": "Кабул", "ja": "カーブル", "ko": "카불"},
    ("Tirana", "Albania"): {"bg": "Тирана", "ja": "ティラナ", "ko": "티라나"},
    ("Algiers", "Algeria"): {"bg": "Алжир", "ja": "アルジェ", "ko": "알제"},
    ("Andorra la Vella", "Andorra"): {"bg": "Андора ла Веля", "ja": "アンドラ・ラ・ベリャ", "ko": "안도라라베야"},
    ("Luanda", "Angola"): {"bg": "Луанда", "ja": "ルアンダ", "ko": "루안다"},
    ("Saint John's", "Antigua and Barbuda"): {"bg": "Сейнт Джонс", "ja": "セントジョンズ", "ko": "세인트존스"},
    ("Buenos Aires", "Argentina"): {"bg": "Буенос Айрес", "ja": "ブエノスアイレス", "ko": "부에노스아이레스"},
    ("Yerevan", "Armenia"): {"bg": "Ереван", "ja": "エレバン", "ko": "예레반"},
    ("Sydney", "Australia"): {"bg": "Сидни", "ja": "シドニー", "ko": "시드니"},
    ("Vienna", "Austria"): {"bg": "Виена", "ja": "ウィーン", "ko": "빈"},
    ("Baku", "Azerbaijan"): {"bg": "Баку", "ja": "バクー", "ko": "바쿠"},
    ("Nassau", "Bahamas"): {"bg": "Насау", "ja": "ナッソー", "ko": "나소"},
    ("Manama", "Bahrain"): {"bg": "Манама", "ja": "マナーマ", "ko": "마나마"},
    ("Dhaka", "Bangladesh"): {"bg": "Дака", "ja": "ダッカ", "ko": "다카"},
    ("Bridgetown", "Barbados"): {"bg": "Бриджтаун", "ja": "ブリッジタウン", "ko": "브리지타운"},
    ("Minsk", "Belarus"): {"bg": "Минск", "ja": "ミンスク", "ko": "민스크"},
    ("Brussels", "Belgium"): {"bg": "Брюксел", "ja": "ブリュッセル", "ko": "브뤼셀"},
    ("Belize City", "Belize"): {"bg": "Белиз Сити", "ja": "ベリーズシティ", "ko": "벨리즈시티"},
    ("Cotonou", "Benin"): {"bg": "Котону", "ja": "コトヌー", "ko": "코토누"},
    ("Thimphu", "Bhutan"): {"bg": "Тхимпху", "ja": "ティンプー", "ko": "팀부"},
    ("La Paz", "Bolivia"): {"bg": "Ла Пас", "ja": "ラパス", "ko": "라파스"},
    ("Sarajevo", "Bosnia and Herzegovina"): {"bg": "Сараево", "ja": "サラエボ", "ko": "사라예보"},
    ("Gaborone", "Botswana"): {"bg": "Габороне", "ja": "ハボローネ", "ko": "가보로네"},
    ("Sao Paulo", "Brazil"): {"bg": "Сао Пауло", "ja": "サンパウロ", "ko": "상파울루"},
    ("Bandar Seri Begawan", "Brunei"): {"bg": "Бандар Сери Бегаван", "ja": "バンダルスリベガワン", "ko": "반다르스리브가완"},
    ("Sofia", "Bulgaria"): {"bg": "София", "ja": "ソフィア", "ko": "소피아"},
    ("Ouagadougou", "Burkina Faso"): {"bg": "Уагадугу", "ja": "ワガドゥグー", "ko": "와가두구"},
    ("Gitega", "Burundi"): {"bg": "Гитега", "ja": "ギテガ", "ko": "기테가"},
    ("Phnom Penh", "Cambodia"): {"bg": "Пном Пен", "ja": "プノンペン", "ko": "프놈펜"},
    ("Douala", "Cameroon"): {"bg": "Дуала", "ja": "ドゥアラ", "ko": "두알라"},
    ("Toronto", "Canada"): {"bg": "Торонто", "ja": "トロント", "ko": "토론토"},
    ("Praia", "Cape Verde"): {"bg": "Прая", "ja": "プライア", "ko": "프라이아"},
    ("Bangui", "Central African Republic"): {"bg": "Банги", "ja": "バンギ", "ko": "방기"},
    ("N'Djamena", "Chad"): {"bg": "Нджамена", "ja": "ンジャメナ", "ko": "은자메나"},
    ("Santiago", "Chile"): {"bg": "Сантяго", "ja": "サンティアゴ", "ko": "산티아고"},
    ("Shanghai", "China"): {"bg": "Шанхай", "ja": "上海", "ko": "상하이"},
    ("Bogota", "Colombia"): {"bg": "Богота", "ja": "ボゴタ", "ko": "보고타"},
    ("Moroni", "Comoros"): {"bg": "Морони", "ja": "モロニ", "ko": "모로니"},
    ("Brazzaville", "Congo"): {"bg": "Бразавил", "ja": "ブラザヴィル", "ko": "브라자빌"},
    ("San Jose", "Costa Rica"): {"bg": "Сан Хосе", "ja": "サンホセ", "ko": "산호세"},
    ("Zagreb", "Croatia"): {"bg": "Загреб", "ja": "ザグレブ", "ko": "자그레브"},
    ("Havana", "Cuba"): {"bg": "Хавана", "ja": "ハバナ", "ko": "하바나"},
    ("Nicosia", "Cyprus"): {"bg": "Никозия", "ja": "ニコシア", "ko": "니코시아"},
    ("Prague", "Czech Republic"): {"bg": "Прага", "ja": "プラハ", "ko": "프라하"},
    ("Prague", "Czechia"): {"bg": "Прага", "ja": "プラハ", "ko": "프라하"},
    ("Copenhagen", "Denmark"): {"bg": "Копенхаген", "ja": "コペンハーゲン", "ko": "코펜하겐"},
    ("Djibouti City", "Djibouti"): {"bg": "Джибути", "ja": "ジブチ", "ko": "지부티"},
    ("Roseau", "Dominica"): {"bg": "Розо", "ja": "ロゾー", "ko": "로조"},
    ("Santo Domingo", "Dominican Republic"): {"bg": "Санто Доминго", "ja": "サントドミンゴ", "ko": "산토도밍고"},
    ("Quito", "Ecuador"): {"bg": "Кито", "ja": "キト", "ko": "키토"},
    ("Cairo", "Egypt"): {"bg": "Кайро", "ja": "カイロ", "ko": "카이로"},
    ("San Salvador", "El Salvador"): {"bg": "Сан Салвадор", "ja": "サンサルバドル", "ko": "산살바도르"},
    ("Malabo", "Equatorial Guinea"): {"bg": "Малабо", "ja": "マラボ", "ko": "말라보"},
    ("Asmara", "Eritrea"): {"bg": "Асмара", "ja": "アスマラ", "ko": "아스마라"},
    ("Tallinn", "Estonia"): {"bg": "Талин", "ja": "タリン", "ko": "탈린"},
    ("Mbabane", "Eswatini"): {"bg": "Мбабане", "ja": "ムババーネ", "ko": "음바바네"},
    ("Addis Ababa", "Ethiopia"): {"bg": "Адис Абеба", "ja": "アディスアベバ", "ko": "아디스아바바"},
    ("Suva", "Fiji"): {"bg": "Сува", "ja": "スバ", "ko": "수바"},
    ("Helsinki", "Finland"): {"bg": "Хелзинки", "ja": "ヘルシンキ", "ko": "헬싱키"},
    ("Paris", "France"): {"bg": "Париж", "ja": "パリ", "ko": "파리"},
    ("Libreville", "Gabon"): {"bg": "Либревил", "ja": "リーブルヴィル", "ko": "리브르빌"},
    ("Banjul", "Gambia"): {"bg": "Банжул", "ja": "バンジュール", "ko": "반줄"},
    ("Tbilisi", "Georgia"): {"bg": "Тбилиси", "ja": "トビリシ", "ko": "트빌리시"},
    ("Berlin", "Germany"): {"bg": "Берлин", "ja": "ベルリン", "ko": "베를린"},
    ("Accra", "Ghana"): {"bg": "Акра", "ja": "アクラ", "ko": "아크라"},
    ("Athens", "Greece"): {"bg": "Атина", "ja": "アテネ", "ko": "아테네"},
    ("Saint George's", "Grenada"): {"bg": "Сейнт Джорджес", "ja": "セントジョージズ", "ko": "세인트조지스"},
    ("Guatemala City", "Guatemala"): {"bg": "Гватемала", "ja": "グアテマラシティ", "ko": "과테말라시티"},
    ("Conakry", "Guinea"): {"bg": "Конакри", "ja": "コナクリ", "ko": "코나크리"},
    ("Bissau", "Guinea-Bissau"): {"bg": "Бисау", "ja": "ビサウ", "ko": "비사우"},
    ("Georgetown", "Guyana"): {"bg": "Джорджтаун", "ja": "ジョージタウン", "ko": "조지타운"},
    ("Port-au-Prince", "Haiti"): {"bg": "Порт-о-Пренс", "ja": "ポルトープランス", "ko": "포르토프랭스"},
    ("Tegucigalpa", "Honduras"): {"bg": "Тегусигалпа", "ja": "テグシガルパ", "ko": "테구시갈파"},
    ("Budapest", "Hungary"): {"bg": "Будапеща", "ja": "ブダペスト", "ko": "부다페스트"},
    ("Reykjavik", "Iceland"): {"bg": "Рейкявик", "ja": "レイキャビク", "ko": "레이캬비크"},
    ("Mumbai", "India"): {"bg": "Мумбай", "ja": "ムンバイ", "ko": "뭄바이"},
    ("Jakarta", "Indonesia"): {"bg": "Джакарта", "ja": "ジャカルタ", "ko": "자카르타"},
    ("Tehran", "Iran"): {"bg": "Техеран", "ja": "テヘラン", "ko": "테헤란"},
    ("Baghdad", "Iraq"): {"bg": "Багдад", "ja": "バグダード", "ko": "바그다드"},
    ("Dublin", "Ireland"): {"bg": "Дъблин", "ja": "ダブリン", "ko": "더블린"},
    ("Jerusalem", "Israel"): {"bg": "Йерусалим", "ja": "エルサレム", "ko": "예루살렘"},
    ("Rome", "Italy"): {"bg": "Рим", "ja": "ローマ", "ko": "로마"},
    ("Abidjan", "Ivory Coast"): {"bg": "Абиджан", "ja": "アビジャン", "ko": "아비장"},
    ("Kingston", "Jamaica"): {"bg": "Кингстън", "ja": "キングストン", "ko": "킹스턴"},
    ("Tokyo", "Japan"): {"bg": "Токио", "ja": "東京", "ko": "도쿄"},
    ("Amman", "Jordan"): {"bg": "Аман", "ja": "アンマン", "ko": "암만"},
    ("Almaty", "Kazakhstan"): {"bg": "Алмати", "ja": "アルマトイ", "ko": "알마티"},
    ("Nairobi", "Kenya"): {"bg": "Найроби", "ja": "ナイロビ", "ko": "나이로비"},
    ("South Tarawa", "Kiribati"): {"bg": "Южна Тарава", "ja": "南タラワ", "ko": "사우스타라와"},
    ("Pristina", "Kosovo"): {"bg": "Прищина", "ja": "プリシュティナ", "ko": "프리슈티나"},
    ("Kuwait City", "Kuwait"): {"bg": "Кувейт", "ja": "クウェートシティ", "ko": "쿠웨이트시티"},
    ("Bishkek", "Kyrgyzstan"): {"bg": "Бишкек", "ja": "ビシュケク", "ko": "비슈케크"},
    ("Vientiane", "Laos"): {"bg": "Виентян", "ja": "ヴィエンチャン", "ko": "비엔티안"},
    ("Riga", "Latvia"): {"bg": "Рига", "ja": "リガ", "ko": "리가"},
    ("Beirut", "Lebanon"): {"bg": "Бейрут", "ja": "ベイルート", "ko": "베이루트"},
    ("Maseru", "Lesotho"): {"bg": "Масеру", "ja": "マセル", "ko": "마세루"},
    ("Monrovia", "Liberia"): {"bg": "Монровия", "ja": "モンロビア", "ko": "몬로비아"},
    ("Tripoli", "Libya"): {"bg": "Триполи", "ja": "トリポリ", "ko": "트리폴리"},
    ("Vaduz", "Liechtenstein"): {"bg": "Вадуц", "ja": "ファドゥーツ", "ko": "파두츠"},
    ("Vilnius", "Lithuania"): {"bg": "Вилнюс", "ja": "ヴィリニュス", "ko": "빌뉴스"},
    ("Luxembourg City", "Luxembourg"): {"bg": "Люксембург", "ja": "ルクセンブルク市", "ko": "룩셈부르크시"},
    ("Antananarivo", "Madagascar"): {"bg": "Антананариво", "ja": "アンタナナリボ", "ko": "안타나나리보"},
    ("Lilongwe", "Malawi"): {"bg": "Лилонгве", "ja": "リロングウェ", "ko": "릴롱궤"},
    ("Kuala Lumpur", "Malaysia"): {"bg": "Куала Лумпур", "ja": "クアラルンプール", "ko": "쿠알라룸푸르"},
    ("Male", "Maldives"): {"bg": "Мале", "ja": "マレ", "ko": "말레"},
    ("Bamako", "Mali"): {"bg": "Бамако", "ja": "バマコ", "ko": "바마코"},
    ("Valletta", "Malta"): {"bg": "Валета", "ja": "バレッタ", "ko": "발레타"},
    ("Majuro", "Marshall Islands"): {"bg": "Маджуро", "ja": "マジュロ", "ko": "마주로"},
    ("Nouakchott", "Mauritania"): {"bg": "Нуакшот", "ja": "ヌアクショット", "ko": "누악쇼트"},
    ("Port Louis", "Mauritius"): {"bg": "Порт Луи", "ja": "ポートルイス", "ko": "포트루이스"},
    ("Mexico City", "Mexico"): {"bg": "Мексико Сити", "ja": "メキシコシティ", "ko": "멕시코시티"},
    ("Palikir", "Micronesia"): {"bg": "Паликир", "ja": "パリキール", "ko": "팔리키르"},
    ("Chisinau", "Moldova"): {"bg": "Кишинев", "ja": "キシナウ", "ko": "키시나우"},
    ("Monaco", "Monaco"): {"bg": "Монако", "ja": "モナコ", "ko": "모나코"},
    ("Ulaanbaatar", "Mongolia"): {"bg": "Улан Батор", "ja": "ウランバートル", "ko": "울란바토르"},
    ("Podgorica", "Montenegro"): {"bg": "Подгорица", "ja": "ポドゴリツァ", "ko": "포드고리차"},
    ("Casablanca", "Morocco"): {"bg": "Казабланка", "ja": "カサブランカ", "ko": "카사블랑카"},
    ("Maputo", "Mozambique"): {"bg": "Мапуту", "ja": "マプト", "ko": "마푸토"},
    ("Yangon", "Myanmar"): {"bg": "Янгон", "ja": "ヤンゴン", "ko": "양곤"},
    ("Windhoek", "Namibia"): {"bg": "Виндхук", "ja": "ウィントフック", "ko": "빈트후크"},
    ("Yaren", "Nauru"): {"bg": "Ярен", "ja": "ヤレン", "ko": "야렌"},
    ("Kathmandu", "Nepal"): {"bg": "Катманду", "ja": "カトマンズ", "ko": "카트만두"},
    ("Amsterdam", "Netherlands"): {"bg": "Амстердам", "ja": "アムステルダム", "ko": "암스테르담"},
    ("Auckland", "New Zealand"): {"bg": "Окланд", "ja": "オークランド", "ko": "오클랜드"},
    ("Managua", "Nicaragua"): {"bg": "Манагуа", "ja": "マナグア", "ko": "마나과"},
    ("Niamey", "Niger"): {"bg": "Ниамей", "ja": "ニアメ", "ko": "니아메"},
    ("Lagos", "Nigeria"): {"bg": "Лагос", "ja": "ラゴス", "ko": "라고스"},
    ("Pyongyang", "North Korea"): {"bg": "Пхенян", "ja": "平壌", "ko": "평양"},
    ("Skopje", "North Macedonia"): {"bg": "Скопие", "ja": "スコピエ", "ko": "스코페"},
    ("Oslo", "Norway"): {"bg": "Осло", "ja": "オスロ", "ko": "오슬로"},
    ("Muscat", "Oman"): {"bg": "Маскат", "ja": "マスカット", "ko": "무스카트"},
    ("Karachi", "Pakistan"): {"bg": "Карачи", "ja": "カラチ", "ko": "카라치"},
    ("Ngerulmud", "Palau"): {"bg": "Нгерулмуд", "ja": "ンゲルルムッド", "ko": "응게룰무드"},
    ("Gaza City", "Palestine"): {"bg": "Газа", "ja": "ガザ", "ko": "가자"},
    ("Panama City", "Panama"): {"bg": "Панама", "ja": "パナマ市", "ko": "파나마시티"},
    ("Port Moresby", "Papua New Guinea"): {"bg": "Порт Морсби", "ja": "ポートモレスビー", "ko": "포트모르즈비"},
    ("Asuncion", "Paraguay"): {"bg": "Асунсион", "ja": "アスンシオン", "ko": "아순시온"},
    ("Lima", "Peru"): {"bg": "Лима", "ja": "リマ", "ko": "리마"},
    ("Manila", "Philippines"): {"bg": "Манила", "ja": "マニラ", "ko": "마닐라"},
    ("Warsaw", "Poland"): {"bg": "Варшава", "ja": "ワルシャワ", "ko": "바르샤바"},
    ("Lisbon", "Portugal"): {"bg": "Лисабон", "ja": "リスボン", "ko": "리스본"},
    ("Doha", "Qatar"): {"bg": "Доха", "ja": "ドーハ", "ko": "도하"},
    ("Bucharest", "Romania"): {"bg": "Букурещ", "ja": "ブカレスト", "ko": "부쿠레슈티"},
    ("Moscow", "Russia"): {"bg": "Москва", "ja": "モスクワ", "ko": "모스크바"},
    ("Kigali", "Rwanda"): {"bg": "Кигали", "ja": "キガリ", "ko": "키갈리"},
    ("Basseterre", "Saint Kitts and Nevis"): {"bg": "Бастер", "ja": "バセテール", "ko": "바스테르"},
    ("Castries", "Saint Lucia"): {"bg": "Кастрийс", "ja": "カストリーズ", "ko": "캐스트리스"},
    ("Kingstown", "Saint Vincent and the Grenadines"): {"bg": "Кингстаун", "ja": "キングスタウン", "ko": "킹스타운"},
    ("Apia", "Samoa"): {"bg": "Апиа", "ja": "アピア", "ko": "아피아"},
    ("San Marino", "San Marino"): {"bg": "Сан Марино", "ja": "サンマリノ", "ko": "산마리노"},
    ("Sao Tome", "Sao Tome and Principe"): {"bg": "Сао Томе", "ja": "サントメ", "ko": "상투메"},
    ("Riyadh", "Saudi Arabia"): {"bg": "Рияд", "ja": "リヤド", "ko": "리야드"},
    ("Dakar", "Senegal"): {"bg": "Дакар", "ja": "ダカール", "ko": "다카르"},
    ("Belgrade", "Serbia"): {"bg": "Белград", "ja": "ベオグラード", "ko": "베오그라드"},
    ("Victoria", "Seychelles"): {"bg": "Виктория", "ja": "ビクトリア", "ko": "빅토리아"},
    ("Freetown", "Sierra Leone"): {"bg": "Фрийтаун", "ja": "フリータウン", "ko": "프리타운"},
    ("Singapore", "Singapore"): {"bg": "Сингапур", "ja": "シンガポール", "ko": "싱가포르"},
    ("Bratislava", "Slovakia"): {"bg": "Братислава", "ja": "ブラチスラヴァ", "ko": "브라티슬라바"},
    ("Ljubljana", "Slovenia"): {"bg": "Любляна", "ja": "リュブリャナ", "ko": "류블랴나"},
    ("Honiara", "Solomon Islands"): {"bg": "Хониара", "ja": "ホニアラ", "ko": "호니아라"},
    ("Mogadishu", "Somalia"): {"bg": "Могадишу", "ja": "モガディシュ", "ko": "모가디슈"},
    ("Johannesburg", "South Africa"): {"bg": "Йоханесбург", "ja": "ヨハネスブルク", "ko": "요하네스버그"},
    ("Seoul", "South Korea"): {"bg": "Сеул", "ja": "ソウル", "ko": "서울"},
    ("Juba", "South Sudan"): {"bg": "Джуба", "ja": "ジュバ", "ko": "주바"},
    ("Madrid", "Spain"): {"bg": "Мадрид", "ja": "マドリード", "ko": "마드리드"},
    ("Colombo", "Sri Lanka"): {"bg": "Коломбо", "ja": "コロンボ", "ko": "콜롬보"},
    ("Khartoum", "Sudan"): {"bg": "Хартум", "ja": "ハルツーム", "ko": "하르툼"},
    ("Paramaribo", "Suriname"): {"bg": "Парамарибо", "ja": "パラマリボ", "ko": "파라마리보"},
    ("Stockholm", "Sweden"): {"bg": "Стокхолм", "ja": "ストックホルム", "ko": "스톡홀름"},
    ("Zurich", "Switzerland"): {"bg": "Цюрих", "ja": "チューリッヒ", "ko": "취리히"},
    ("Damascus", "Syria"): {"bg": "Дамаск", "ja": "ダマスカス", "ko": "다마스쿠스"},
    ("Taipei", "Taiwan"): {"bg": "Тайпе", "ja": "台北", "ko": "타이베이"},
    ("Dushanbe", "Tajikistan"): {"bg": "Душанбе", "ja": "ドゥシャンベ", "ko": "두샨베"},
    ("Dar es Salaam", "Tanzania"): {"bg": "Дар ес Салаам", "ja": "ダルエスサラーム", "ko": "다르에스살람"},
    ("Bangkok", "Thailand"): {"bg": "Банкок", "ja": "バンコク", "ko": "방콕"},
    ("Dili", "Timor-Leste"): {"bg": "Дили", "ja": "ディリ", "ko": "딜리"},
    ("Lome", "Togo"): {"bg": "Ломе", "ja": "ロメ", "ko": "로메"},
    ("Nuku'alofa", "Tonga"): {"bg": "Нукуалофа", "ja": "ヌクアロファ", "ko": "누쿠알로파"},
    ("Port of Spain", "Trinidad and Tobago"): {"bg": "Порт ъф Спейн", "ja": "ポートオブスペイン", "ko": "포트오브스페인"},
    ("Tunis", "Tunisia"): {"bg": "Тунис", "ja": "チュニス", "ko": "튀니스"},
    ("Istanbul", "Turkey"): {"bg": "Истанбул", "ja": "イスタンブール", "ko": "이스탄불"},
    ("Ashgabat", "Turkmenistan"): {"bg": "Ашхабад", "ja": "アシガバート", "ko": "아슈하바트"},
    ("Funafuti", "Tuvalu"): {"bg": "Фунафути", "ja": "フナフティ", "ko": "푸나푸티"},
    ("Kampala", "Uganda"): {"bg": "Кампала", "ja": "カンパラ", "ko": "캄팔라"},
    ("Kyiv", "Ukraine"): {"bg": "Киев", "ja": "キーウ", "ko": "키이우"},
    ("Dubai", "United Arab Emirates"): {"bg": "Дубай", "ja": "ドバイ", "ko": "두바이"},
    ("London", "United Kingdom"): {"bg": "Лондон", "ja": "ロンドン", "ko": "런던"},
    ("New York", "United States"): {"bg": "Ню Йорк", "ja": "ニューヨーク", "ko": "뉴욕"},
    ("Montevideo", "Uruguay"): {"bg": "Монтевидео", "ja": "モンテビデオ", "ko": "몬테비데오"},
    ("Tashkent", "Uzbekistan"): {"bg": "Ташкент", "ja": "タシュケント", "ko": "타슈켄트"},
    ("Port Vila", "Vanuatu"): {"bg": "Порт Вила", "ja": "ポートビラ", "ko": "포트빌라"},
    ("Vatican City", "Vatican City"): {"bg": "Ватикан", "ja": "バチカン", "ko": "바티칸"},
    ("Caracas", "Venezuela"): {"bg": "Каракас", "ja": "カラカス", "ko": "카라카스"},
    ("Ho Chi Minh City", "Vietnam"): {"bg": "Хошимин", "ja": "ホーチミン", "ko": "호찌민"},
    ("Sanaa", "Yemen"): {"bg": "Сана", "ja": "サナア", "ko": "사나"},
    ("Lusaka", "Zambia"): {"bg": "Лусака", "ja": "ルサカ", "ko": "루사카"},
    ("Harare", "Zimbabwe"): {"bg": "Хараре", "ja": "ハラレ", "ko": "하라레"},
}

# Well-known non-capitals already in CITY_I18N — same three locales so they
# do not fall back to an English pair.
MAJOR_CITY_I18N: Final[dict[tuple[str, str], dict[str, str]]] = {
    ("Beijing", "China"): {"bg": "Пекин", "ja": "北京", "ko": "베이징"},
    ("Cologne", "Germany"): {"bg": "Кьолн", "ja": "ケルン", "ko": "쾰른"},
    ("Dusseldorf", "Germany"): {"bg": "Дюселдорф", "ja": "デュッセルドルフ", "ko": "뒤셀도르프"},
    ("Florence", "Italy"): {"bg": "Флоренция", "ja": "フィレンツェ", "ko": "피렌체"},
    ("Frankfurt", "Germany"): {"bg": "Франкфурт", "ja": "フランクフルト", "ko": "프랑크푸르트"},
    ("Geneva", "Switzerland"): {"bg": "Женева", "ja": "ジュネーヴ", "ko": "제네바"},
    ("Guangzhou", "China"): {"bg": "Гуанджоу", "ja": "広州", "ko": "광저우"},
    ("Hanoi", "Vietnam"): {"bg": "Ханой", "ja": "ハノイ", "ko": "하노이"},
    ("Hong Kong", "China"): {"bg": "Хонконг", "ja": "香港", "ko": "홍콩"},
    ("Los Angeles", "United States"): {"bg": "Лос Анджелис", "ja": "ロサンゼルス", "ko": "로스앤젤레스"},
    ("Milan", "Italy"): {"bg": "Милано", "ja": "ミラノ", "ko": "밀라노"},
    ("Montreal", "Canada"): {"bg": "Монреал", "ja": "モントリオール", "ko": "몬트리올"},
    ("Munich", "Germany"): {"bg": "Мюнхен", "ja": "ミュンヘン", "ko": "뮌헨"},
    ("Naples", "Italy"): {"bg": "Неапол", "ja": "ナポリ", "ko": "나폴리"},
    ("Osaka", "Japan"): {"bg": "Осака", "ja": "大阪", "ko": "오사카"},
    ("Saint Petersburg", "Russia"): {"bg": "Санкт Петербург", "ja": "サンクトペテルブルク", "ko": "상트페테르부르크"},
    ("Shenzhen", "China"): {"bg": "Шенжен", "ja": "深圳", "ko": "선전"},
    ("The Hague", "Netherlands"): {"bg": "Хага", "ja": "ハーグ", "ko": "헤이그"},
    ("Delhi", "India"): {"bg": "Делхи", "ja": "デリー", "ko": "델리"},
    ("Chennai", "India"): {"bg": "Ченай", "ja": "チェンナイ", "ko": "첸나이"},
    ("Kolkata", "India"): {"bg": "Колката", "ja": "コルカタ", "ko": "콜카타"},
}
